### ISSUE TITLE
Create a new native app does not run.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [react-native-community/cli#649] opened 2019-08-26 22:29 UTC
## Environment

System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 271.98 MB / 7.71 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7

## Description

When I created a new app using ```npx react-native init newapp```, cli stops after this 
```
27 actionable tasks: 3 executed, 24 up-to-date
info Connecting to the development server...
info Starting the app on "b610d425"...
Starting: Intent { cmp=com.newapp/.MainActivity }
```
and the app on device shows red screen with unable to load scripts.

![WhatsApp Image 2019-08-27 at 4 16 17 AM](https://user-images.githubusercontent.com/16081083/63728499-90f7b500-c881-11e9-8baf-a03b6ba0b6bd.jpeg)
## Reproducible Demo
Just create a new app.

**Comment by thymikee** [comment] 2019-08-26 22:40
Can you share what's on the red screen? We need more details

**Comment by a-c-sreedhar-reddy** [comment] 2019-08-26 22:49
@thymikee updated the comment.

**Comment by thymikee** [comment] 2019-08-27 06:18
You need to be on a WiFi connection, looks like you aren't.

**Comment by a-c-sreedhar-reddy** [comment] 2019-08-27 06:57
I have connected my device via USB.

**Comment by thymikee** [comment] 2019-08-27 07:36
You still need to connect to the same WiFi network for Metro server to see your device. It is expected behavior that CLI exits after starting intent. Closing, as this is an issue with your environment.

**Closed by thymikee** 2019-08-27 07:36 UTC
Labels: bug

**Comment by a-c-sreedhar-reddy** [comment] 2019-08-27 07:44
@thymikee I connected to the same network and tried. But still the issue exist.

**Comment by thymikee** [comment] 2019-08-27 08:00
Hope this helps: https://facebook.github.io/react-native/docs/running-on-device.html

**Comment by a-c-sreedhar-reddy** [comment] 2019-08-27 08:48
@thymikee Solved this issue .
 1) ran `react-native start` in one console.
 2) ran `react-native run-android` in another console. This uploaded the app and stopped. But the app loaded js bundle from 1).

Dont know if this the way it should be done or is it  a bug.

**Comment by thymikee** [comment] 2019-08-27 08:50
It's hard to say without reproducing the environment. But I wouldn't bother if it works this way. I, for example, always run `start` and `run-*` separately because I like to place them in a certain way on my terminal window :D
