### ISSUE TITLE
Cannot get property 'packageName' on null object

### ISSUE THREAD

**Issue by brunolemos** [react-native-community/cli#655] opened 2019-09-01 07:14 UTC
> Moving from #537

## Environment

System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 2.70 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.8.0 - /var/folders/xh/gcxkb1qx2rd3fmqz5vxrs2lh0000gn/T/yarn--1567321836628-0.386672585258681/node
    Yarn: 1.17.3 - /var/folders/xh/gcxkb1qx2rd3fmqz5vxrs2lh0000gn/T/yarn--1567321836628-0.386672585258681/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild

## Description

Can't get react-native 0.61 to work on a monorepo on Android. Build fails with the error: `Cannot get property 'packageName' on null object`. iOS works as expected.

Running `yarn react-native config` returns this result:

```
{
  "root": "/Users/user/Projects/react-native-web-monorepo",
  "reactNativePath": "/Users/user/Projects/react-native-web-monorepo/node_modules/react-native",
  "dependencies": {},
  "commands": [],
  "assets": [],
  "platforms": {},
  "haste": {
    "providesModuleNodeModules": [],
    "platforms": []
  },
  "project": {}
}
```

Using `nohoist` or installing `react-native` inside `packages/mobile` instead of the root is not an option because that causes a range of other issues. 

## Reproducible Demo

Branch `rn61` with error: https://github.com/brunolemos/react-native-web-monorepo/tree/rn61
Branch `master` working, with [workarounds](https://github.com/react-native-community/cli/issues/655#issuecomment-531899969): https://github.com/brunolemos/react-native-web-monorepo

**Comment by subashtimalsina** [comment] 2019-09-03 11:55
I am also facing the same problem though my react-native version is 0.59, I couldn't fix this issue. If you have any optional idea please share me.

**Comment by bensonyang2015** [comment] 2019-09-04 06:26
I met the same problem and I got it to work by adding a file `react-native.config.js` to describe my custom android project info.
check this [document](https://github.com/react-native-community/cli/blob/master/docs/projects.md).

**Comment by brunolemos** [comment] 2019-09-04 19:57
Is it possible to upgrade to react-native 0.61 on a monorepo while this is not fixed? Any older version of `@react-native-community/cli` I can use that would work? I'm holding off upgrading just because of this.

**Comment by Blizard** [comment] 2019-09-06 07:28
We have exactly the same problem for 0.56.5. Same project structure setup. We've got this error when we set autolinking as it's described [here](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#platform-android). 

Any idea what to do?

**Comment by brunolemos** [comment] 2019-09-06 23:09
I was able to workaround this issue by disabling auto linking. Here's the [commit diff](https://github.com/brunolemos/react-native-web-monorepo/commit/8698c7acb88d37ea5396132223266b8fc7b002f1).

But I'm still stuck at 0.59 because when trying to upgrade to 0.60.5 I get [this error](https://github.com/facebook/react-native/issues/25552) and to 0.61 I get something similar to [this error](https://github.com/facebook/react-native/pull/26151#issuecomment-526684201).

**Comment by brunolemos** [comment] 2019-09-16 18:29
Successfully upgraded to react-native 0.61 here: https://github.com/brunolemos/react-native-web-monorepo

I did have to add “react-native” dependency to the root package.json though. Not a big deal but hopefully that get fixed.

**Comment by joaovpmamede** [comment] 2019-09-20 10:07
@brunolemos is auto linking working for you on this new version?

**Comment by brunolemos** [comment] 2019-09-20 16:56
@joaovpmamede haven't tried yet, please fork and try: https://github.com/brunolemos/react-native-web-monorepo

**Comment by luco** [comment] 2019-09-20 19:17
Getting this as well.

**Comment by joaovpmamede** [comment] 2019-09-20 20:48
Auto link didn't work for me.

**Comment by Jyrno42** [comment] 2019-09-24 11:53
Having same issue with an example app of a package which contains no native modules

**Comment by grabbou** [comment] 2019-10-03 15:59
@brunolemos 

> I did have to add `react-native` dependency to the root package.json and create a react-native.config.js though. Not a big deal but hopefully that gets fixed, this workaround was not necessary on <= 0.59.

I have tried your repository and I don't think this is a correct way to run things. 

The problem that appears here is that you have set `sourceDir` to be `packages/mobile/android`. That makes `react-native config` output `android: null`, which produces the auto-linking error.

I have removed this file entirely and run `react-native config` from within the `packages/mobile` (`cd ./packages/mobile && yarn react-native config`) and the configuration file looks and works okay.

I don't think this is a recommended way of setting things up. The CLI should always be run from the folder where React Native files are located. The location of `node_modules` and React Native itself shouldn't be relevant (there's already a way to configure `reactNativePath`).

I am going to close this issue and re-open #537. I am going to re-work `monorepo` support so that it works automatically without specifying a custom root.

**Comment by grabbou** [comment] 2019-10-03 16:22
One thing we should do here is to "always resolve paths within configuration, relatively to the location of the configuration file".

**Comment by brunolemos** [comment] 2019-10-06 01:47
>  is auto linking working for you on this new version?
> Auto link didn't work for me.

I'm trying to update another project and autolink did work for me on ios, but not on android.

> The problem that appears here is that you have set sourceDir to be <root>/packages/mobile/android.

I only added `sourceDir` to fix this `Cannot get property 'packageName' on null object` error, so I definitely wouldn't say it is the cause of the error but the workaround to get it working

**Comment by Hugo-Meiring** [comment] 2019-10-08 09:39
Can confirm:

"Cannot get property 'packageName' on null object" happens on RN 0.61.0-rc3. Only Android is not building

**Closed** 2019-10-08 20:12 UTC
Labels: bug

**Comment by mllw** [comment] 2019-10-16 08:05
> @brunolemos
> 
> > I did have to add `react-native` dependency to the root package.json and create a react-native.config.js though. Not a big deal but hopefully that gets fixed, this workaround was not necessary on <= 0.59.
> 
> I have tried your repository and I don't think this is a correct way to run things.
> 
> The problem that appears here is that you have set `sourceDir` to be `<root>/packages/mobile/android`.
> 
> The CWD is: `<root>/packages/mobile` at the time of running your script (via `yarn workspace mobile`).
> 
> As a result, React Native CLI tries to look for Android files inside `<root>/packages/mobile/packages/mobile/android`, which produces `null` and as a result, makes Android files check for `packageName` of null.
> 
> Right now, the paths are relative to the `CWD`. Maybe they should be relative to the location of the configuration file, but that would be a change.



> > Moving from #537
> 
> ## Environment
> System:
> OS: macOS 10.15
> CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
> Memory: 2.70 GB / 16.00 GB
> Shell: 5.7.1 - /bin/zsh
> Binaries:
> Node: 12.8.0 - /var/folders/xh/gcxkb1qx2rd3fmqz5vxrs2lh0000gn/T/yarn--1567321836628-0.386672585258681/node
> Yarn: 1.17.3 - /var/folders/xh/gcxkb1qx2rd3fmqz5vxrs2lh0000gn/T/yarn--1567321836628-0.386672585258681/yarn
> npm: 6.10.3 - /usr/local/bin/npm
> Watchman: 4.9.0 - /usr/local/bin/watchman
> SDKs:
> iOS SDK:
> Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
> Android SDK:
> API Levels: 28
> Build Tools: 28.0.3
> IDEs:
> Android Studio: 3.5 AI-191.8026.42.35.5791312
> Xcode: 10.3/10G8 - /usr/bin/xcodebuild
> 
> ## Description
> Can't get react-native 0.61 to work on a monorepo on Android. Build fails with the error: `Cannot get property 'packageName' on null object`. iOS works as expected.
> 
> Running `yarn react-native config` returns this result:
> 
> ```
> {
>   "root": "/Users/user/Projects/react-native-web-monorepo",
>   "reactNativePath": "/Users/user/Projects/react-native-web-monorepo/node_modules/react-native",
>   "dependencies": {},
>   "commands": [],
>   "assets": [],
>   "platforms": {},
>   "haste": {
>     "providesModuleNodeModules": [],
>     "platforms": []
>   },
>   "project": {}
> }
> ```
> 
> Using `nohoist` or installing `react-native` inside `packages/mobile` instead of the root is not an option because that causes a range of other issues.
> 
> ## Reproducible Demo
> Branch `rn61` with error: https://github.com/brunolemos/react-native-web-monorepo/tree/rn61
> Branch `master` working, with [workarounds](https://github.com/react-native-community/cli/issues/655#issuecomment-531899969): https://github.com/brunolemos/react-native-web-monorepo

I modify node_modules/@react-native-community/cli-platform-android/native_modules.gradle 
at line 157 
cmdProcess = Runtime.getRuntime().exec(command) 
change to
cmdProcess = Runtime.getRuntime().exec(command,null,new File(System.getProperty("user.dir")).getParentFile())
work OK

**Comment by gaozhaoqun** [comment] 2019-10-24 01:27
@mllw  thank you!!!

**Comment by detroit007** [comment] 2019-10-28 07:31
@gaozhaoqun did you find solution ? if yes then share pls!

**Comment by chawlatarika5** [comment] 2019-10-30 19:08
The solution is there:
Go to the node_modules/@react-native-community/cli-platform-android/native_modules.gradle
at line 157 (or find cmdProcess)
Is should be something like this:
```cmdProcess = Runtime.getRuntime().exec(command)```
Change it to
```cmdProcess = Runtime.getRuntime().exec(command,null,new File(System.getProperty("user.dir")).getParentFile())```

**Comment by johnshroff** [comment] 2019-10-31 13:29
@mllw suggestion worked for me!

**Comment by alisabrigok** [comment] 2019-11-05 18:33
I don't think it's a good idea to change any code that is inside node_modules folder. Since it's added via npm and ignored by git any changes you will make end up staying only on your local.

However, there's another solution that's mentioned in one of the recently opened issues. See https://github.com/react-native-community/cli/issues/835#issuecomment-549134018

Basically, add cli-platform-android package to your dev dependencies:

`npm install @react-native-community/cli-platform-android --save-dev`

This solved my problem and seems safer. @mllw @gaozhaoqun @detroit007 @chawlatarika5 @johnshroff

**Comment by jakewtaylor** [comment] 2019-11-08 17:07
I'm also having this problem - @chawlatarika5's solution is working for me but obviously isn't ideal.

Some coworkers are able to run the same project with no issues, without editing node_modules. We can't spot any difference in environment - we're stumped!

**Comment by Glinkis** [comment] 2019-11-14 08:16
@chawlatarika5's solution does not work for me, as I still get the exact same error.

**Comment by julianD77** [comment] 2019-11-26 15:36
I was having a similar problem with this error message and then found that it was caused by a syntax error in my `package.json` (a missing comma 😞), so it is worth verifying that file is correctly formatted if it has been changed recently

**Comment by karlmarxlopez** [comment] 2020-07-04 08:18
To everyone complaining it is a bad idea to modify content of `@react-native-community/cli-platform-android`, you can use `patch-package` and run it after npm or yarn install, without worrying your modifications to be overwritten.

1. Modify cli-platform-android
2. Run `npx patch-package @react-native-community/cli-platform-android`
3. Add this to your `package.json`, under `scripts`.
`postinstall: "npx patch-package`

**Comment by FMaz008** [comment] 2020-12-10 02:41
I am still getting this error running react-native 0.63.4


```
Execution failed for task ':app:generateDebugBuildConfig'.
> Failed to calculate the value of task ':app:generateDebugBuildConfig' property 'buildConfigPackageName'.
   > Failed to query the value of property 'packageName'.
      > java.lang.NumberFormatException: For input string: "1.0.0"
```
