### ISSUE TITLE
run-android fails in custom project structure

### ISSUE THREAD

**Issue by BharathMG-ShareChat** [react-native-community/cli#956] opened 2020-02-12 08:16 UTC
My project structure looks like this,

```
- appName
   -- reactNative // React native package.json, node_modules,...
   -- app // Android app folder
```

If I run, "npx react-native run-droid" inside `reactNative` folder, it fails with,

```
error Android project not found. Are you sure this is a React Native project?
```

This is because, cli checks for `android/gradlew` inside root folder which is not there in my project structure. It is in `appName/gradlew`. How can I change this gradlew path in cli command?

**Comment by thymikee** [comment] 2020-02-12 08:20
You can either create a `react-native.config.js` file in the project root, or run the command from the project root, or both.

**Comment by BharathMG-ShareChat** [comment] 2020-02-12 09:07
@thymikee I thought run-android doesn't use config yet. I saw your PR https://github.com/react-native-community/cli/pull/791 fixes this issue. Not sure if I'm missing something. Could you point me to a sample `react-native.config.js` file for custom project structure? Thanks!

**Comment by thymikee** [comment] 2020-02-12 09:13
Having `react-native.config.js` in a directory is a trick to tell the CLI that "here's the root of the project, let's look up from there".

Sample config:
```js
module.exports = {};
```

**Comment by grabbou** [comment] 2020-02-17 02:57
Aside from that, yeah, this is a duplicate of #791 that @thymikee was/is working on. I am working on cleaning up the `next` branch and we will resume work no that.

**Closed by grabbou** 2020-02-17 02:57 UTC
Labels: question
