### ISSUE TITLE
Android build fails: Cannot find module 'react-native/cli' 

### ISSUE THREAD

**Issue by dusanjovanov** [react-native-community/cli#1059] opened 2020-03-18 16:19 UTC
## Environment

System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 25.00 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.0 - /var/folders/fg/gm8zrwkn5cdf0y2bpnz4b1vw0000gp/T/yarn--1584547289822-0.2988143202810205/node
    Yarn: 1.22.0 - /var/folders/fg/gm8zrwkn5cdf0y2bpnz4b1vw0000gp/T/yarn--1584547289822-0.2988143202810205/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-R | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^4.3.0 => 4.3.0 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Description

When trying to build an Android app on Microsoft App Center, I get this error:
<img width="1187" alt="Screenshot at Mar 18 17-12-12" src="https://user-images.githubusercontent.com/20474783/76982290-f4d7ed00-693b-11ea-967f-49104165b5cf.png">

I think that this is what's causing the problem:
`node, -e, console.log(require('react-native/cli').bin);`
Because the command is run from the root of the repo and the react native project is one level down. 

## Reproducible Demo

This would be trying to build an Android App on MS App Center, while the react native project is not in the root of the repository.

**Comment by thymikee** [comment] 2020-03-18 16:33
Duplicate of #995

**Closed by thymikee** 2020-03-18 16:33 UTC
Labels: bug report
