### ISSUE TITLE
Can't regenerate ios project

### ISSUE THREAD

**Issue by liftyourgame** [react-native-community/cli#895] opened 2019-12-18 09:33 UTC
## Environment

System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 224.05 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 25, 28
      Build Tools: 25.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-eject: 0.1.2
    react-native: 0.61.5

## Description

You used to be able to regenerate an ios project with:
react-native eject
or
react-native upgrade --legacy true

This no longer works.

## Reproducible Demo

This stackoverflow issue talks about this issue:
https://stackoverflow.com/questions/42506068/how-can-i-regenerate-ios-folder-in-react-native-project

What is the recommended way to regen the android.ios projects?

Surely you don't expect us to downgrade react-native-cli to do something that used to be possible?

**Comment by thymikee** [comment] 2019-12-18 09:37
Kinda duplicate of #503. Please see the discussion there.

**Closed by thymikee** 2019-12-18 09:37 UTC
Labels: bug report
