### ISSUE TITLE
Cannot push project to gitlab repo with SSH

### ISSUE THREAD

**Issue by DevPranavSharma** [react-native-community/cli#1416] opened 2021-05-12 07:25 UTC
## Environment

OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 54.96 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
## Description
 I try to init a project using react-native CLI and push to Gitlab using SSH , the command breaks and gives the following error

Received disconnect from IP port 22:2: Packet corrupt
Disconnected from IP port 22
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly

The issue is only occurring with react-native and other repositories are working fine.

**Comment by Esemesek** [comment] 2021-10-08 11:41
This doesn't seem like a `react-native-cli` issue to me. You have to remember that the react-native template is quite big and contains a lot of types of files including binary files. Maybe this is the cause of the issue. Anyway, closing.

**Closed by Esemesek** 2021-10-08 11:41 UTC
Labels: bug report
