### ISSUE TITLE
Fails to upgrade while version is specified. 

### ISSUE THREAD

**Issue by scerelli** [react-native-community/cli#476] opened 2019-07-05 09:07 UTC
## Environment

```
 React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
      Memory: 1.23 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
```

## Description
I'm trying to upgrade from `0.59.8` to ` 0.59.10` but i get this message:
![Screenshot 2019-07-05 at 10 49 11](https://user-images.githubusercontent.com/4821190/60710431-ff1f9b80-9f12-11e9-9c4f-c991a6cdb3fe.png)

I checked the code and by reading it I suppose it must be something related to this function:
https://github.com/react-native-community/cli/blob/870a4e2ae07f5859deb08d4ca468536f4bb6e787/packages/cli/src/commands/upgrade/upgrade.js#L96

## Reproducible Demo
Create a react-native project with a version lower than 0.59.10 and run `react-native upgrade 0.59.10`

**Comment by thymikee** [comment] 2019-07-05 09:09
Duplicate of https://github.com/react-native-community/cli/issues/456. Fixed in a patch release.

**Closed by thymikee** 2019-07-05 09:09 UTC
Labels: bug
