### ISSUE TITLE
Metro Bundler immediately closes after react-native run-android

### ISSUE THREAD

**Issue by theweavrs** [react-native-community/cli#484] opened 2019-07-05 14:04 UTC
## Environment
```
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 8.99 GB / 15.89 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      Android NDK: 18.1.5063045
  IDEs:
    Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788
```
```
react-native-cli: 2.0.1
react-native: 0.60.0
```
## Description
Doing `yarn react-native run-android` opens the `metro bundler` but it immediately closes. Don't know if its a bug with the `cli` or the `metro` itself. This only happens on Windows, I think.

Things I have tried:
1. Restarting my system
2. Clearing cache etc.

## Reproducible Demo
1. Create a new project using `react-native init`
2. Run `yarn react-native run-android`

**Comment by thymikee** [comment] 2019-07-05 14:24
We'll need help debugging what's causing this. What does it mean that "it closes"? Can you share more details?

**Comment by theweavrs** [comment] 2019-07-05 14:27
@thymikee well I can't see the error on it as it only blinks. How can I debug it?

**Comment by thymikee** [comment] 2019-07-05 14:30
Can you post a video? :D Set up some console.logs in `commands/server/runServer.js`

**Comment by theweavrs** [comment] 2019-07-05 14:52
@thymikee runServer gives nothing so it's not even getting there.

**Comment by thymikee** [comment] 2019-07-05 14:56
Btw, does running `yarn react-native start` works without issues? If so, check files related to this diff: https://github.com/react-native-community/cli/pull/310

**Comment by theweavrs** [comment] 2019-07-05 14:56
Running `launchPackager.bat` directly gives this error:
`error: unknown option `--projectRoot'`

**Comment by theweavrs** [comment] 2019-07-05 15:03
Doing `yarn react-native start` gives me the console.logs I had set so I am guessing, `runServer` is getting called in that case.

**Comment by theweavrs** [comment] 2019-07-05 15:04
Running `node .\node_modules\react-native\cli.js --projectRoot` also gives this error:
error: unknown option `--projectRoot'

**Comment by thymikee** [comment] 2019-07-05 15:05
Yea, because we removed this option. It's not necessary now. Can you remove it from https://github.com/facebook/react-native/blob/master/scripts/launchPackager.bat and see if that works?

**Comment by theweavrs** [comment] 2019-07-05 15:06
@thymikee yup. Working without a hitch.

**Comment by thymikee** [comment] 2019-07-05 15:07
Yea, can you send a PR to RN? The patch release make take a while (cc @kelset). I think we should own these files, but that may be a bit bigger change.

**Comment by theweavrs** [comment] 2019-07-05 15:08
@thymikee okay, I will do that.

**Comment by zenz** [comment] 2019-07-05 15:09
removing node_modules/react-native/scripts/launchPackager.bat then even the splash window of Metro Bundler will not show, of course it's not running.

**Comment by thymikee** [comment] 2019-07-05 15:11
@zenz it's not about rmeoving the file, but doing this diff:
```diff
-node "%~dp0..\cli.js" --projectRoot ../../../ start
+node "%~dp0..\cli.js" start
```

**Comment by zenz** [comment] 2019-07-05 15:12
@thymikee  oops... yes, it's working now.

**Comment by theweavrs** [comment] 2019-07-05 15:12
@thymikee can't we ship a temporary fix with the cli until RN releases the fix?

**Comment by thymikee** [comment] 2019-07-05 15:13
If you'd like to contribute this then of yea. I don't have too much bandwidth currently, just trying to be helpful.

**Comment by zenz** [comment] 2019-07-05 15:18
It seems that another problem raised after modify this launchPackager.bat file. Metro Bundler tells me there's no index file
`Error: Unable to resolve module `./index` from `C:\Users\zenz\programs\test_app\node_modules\react-native\scripts/.`: The module `./index` could not be found from `C:\Users\zenz\programs\test_app\node_modules\react-native\scripts/.`. Indeed, none of these files exist:`
But using react-native start to start the Metro Bundler is working correctly.

**Comment by victorwpbastos** [comment] 2019-07-05 15:21
@zenz same here. I changed `lanchPackager.bat`, Metro bundler shows up, but with this error.

**Comment by victorwpbastos** [comment] 2019-07-05 15:22
Maybe `projectRoot` parameter is necessary after all.

**Comment by zenz** [comment] 2019-07-05 15:22
modify it like this, solves the problem:
```
@echo off
title Metro Bundler
call .packager.bat
cd ../../../
node "%~dp0..\cli.js" start
pause
exit

```

**Comment by thymikee** [comment] 2019-07-05 15:24
I think that makes sense, this is similar to what Linux script does: https://github.com/facebook/react-native/blob/master/scripts/launchPackager.command

**Comment by theweavrs** [comment] 2019-07-05 15:26
@thymikee should I add it to the PR?

**Comment by thymikee** [comment] 2019-07-05 15:27
Let's make sure it works as intended, and then yes

**Comment by theweavrs** [comment] 2019-07-05 15:29
@thymikee after adding the `cd` command, the packager loads and bundles successfully. So it is working.

**Comment by victorwpbastos** [comment] 2019-07-05 15:32
After the `cd ../../../` command, it works successfully!

**Comment by Inovassist-dev** [comment] 2019-07-05 22:58
Hey guys, still having problems...
Today I started a new RN project, after the setupe, my Metro Bundler opens, starts, but it keeps in the "Loading Depedency Graph..." screen. It starts to consume my computer memory like crazy and everything gets really slow, but the Metro Bundler don't finish the Dependency Graph proccess.
Any workaround to that?

P.S.: I already tried the steps above!

**Comment by zenz** [comment] 2019-07-05 23:45
@Inovassist-dev
kill all background node process, run 
react-native start 
is it running correct or not?

**Comment by Andersonfrfilho** [comment] 2019-07-06 03:41
Thx, zenz 
I have this problem

Environment
```
System:
    OS: Windows 10
Yarn version: 
  1.16.0

Node version: 
  10.15.3

Platform: 
  win32 x64
```
react-native --version
```
react-native-cli: 2.0.1
react-native: 0.60.0
```
react-native run-android

`D:\ADS\curso-react-native\ReactNativeReduxGraphQl>react-native run-android
info Starting JS server...
info Installing the app...

> Task :app:installDebug
01:20:29 V/ddms: execute: running am get-config
01:20:29 V/ddms: execute 'am get-config' on 'emulator-5554' : EOF hit. Read: -1
01:20:29 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'Pixel_3_API_28_86(AVD) - 9' for app:debug
01:20:29 D/app-debug.apk: Uploading app-debug.apk onto device 'emulator-5554'
01:20:29 D/Device: Uploading file onto device 'emulator-5554'
01:20:29 D/ddms: Reading file permision of D:\ADS\curso-react-native\ReactNativeReduxGraphQl\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
01:20:29 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
01:20:30 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
01:20:30 V/ddms: execute: returning
01:20:30 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
01:20:30 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
01:20:30 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3s
27 actionable tasks: 2 executed, 25 up-to-date
'C:\Users\Anderson' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
info Connecting to the development server...
info Starting the app...
Starting: Intent { cmp=com.reactnativereduxgraphql/.MainActivity }

D:\ADS\curso-react-native\ReactNativeReduxGraphQl>`


Works only by executing commands
1st react-native start
2nd react-native run-android

or manually
the project repositori
https://github.com/Andersonfrfilho/ReactNativeReduxGraphQl

**Comment by theweavrs** [comment] 2019-07-06 03:52
@Andersonfrfilho I don't see any error in your output. What's the problem?

**Comment by zenz** [comment] 2019-07-06 03:58
I run @Andersonfrfilho 's code with modifyed launchPackager.bat.
No errors and it runs well.

So I think he didn't modify the launchPackager.bat file

**Comment by theweavrs** [comment] 2019-07-06 06:40
Just created a PR (#489) that should fix this for now. @thymikee waiting for your review.

**Comment by zenz** [comment] 2019-07-06 07:49
@theweavrs good, this PR moves the commands into same place.

**Comment by ruhaim** [comment] 2019-07-06 09:17
> Just created a PR (#489) that should fix this for now. @thymikee waiting for your review.

when i applied the pr, i get a "fs is not defined error"

**Comment by EnKrypt** [comment] 2019-07-06 09:45
This is kind of sad. How do new releases get rolled out without some basic checks?

I assume this is breaking for everyone using Windows, given that I found this issue organically after facing the same issue, and I'm sure more will find this issue after me, wondering what on earth could have gone wrong.

**Comment by EnKrypt** [comment] 2019-07-06 10:02
As a temporary solution, I've found a little workaround :

* Run the Metro Bundler manually  with `react-native start`

* Then run as usual. I'm doing `react-native run-android`

You might be stuck with a blank screen after this, meaning you have to run again after Metro generated a build/bundle once. So force close the app, and then run as usual again while keeping the Metro Bundler running in the background.

You may also have to update your version of `react-native-cli` to 2.0.2

**Comment by Andersonfrfilho** [comment] 2019-07-06 12:46
Good as I saw the difficulty to find the error I posted a video showing what is happening now when I execute the commands
https://youtu.be/6qiBeKnHYSc
thank you to the impenetrate for trying to solve the problem

**Comment by zenz** [comment] 2019-07-06 13:08
@Andersonfrfilho 
Please read above comments to find out the temporary solution.
Modify node_modules/react-native/scripts/launchPackager.bat
Change the contents like below:
```
@echo off
title Metro Bundler
call .packager.bat
cd ../../../
node "%~dp0..\cli.js" start
pause
exit
```

**Comment by Andersonfrfilho** [comment] 2019-07-06 13:23
Again I apologize for the inconvenience, but there is neither this executable nor the file in my node_modules

img:
https://ibb.co/kBnmCzG

**Comment by thymikee** [comment] 2019-07-06 13:35
@Andersonfrfilho the path is `./node_modules/react-native/scripts/launchPackager.bat`, please read carefully.

**Comment by Andersonfrfilho** [comment] 2019-07-06 13:43
sorry, I just review here I'll try, thx

**Comment by Andersonfrfilho** [comment] 2019-07-07 00:32
Hey guys worked with the change in the .bat file ok, vlw but once thanks. Sorry for the inconvenience

**Comment by thymikee** [comment] 2019-07-07 08:56
Closed via https://github.com/react-native-community/cli/pull/489. Published in 2.1.1, please try give it a try (see how to [update the CLI](https://github.com/react-native-community/cli#updating-the-cli))

**Closed by thymikee** 2019-07-07 08:56 UTC
Labels: bug, help wanted, platform: windows

**Comment by naderabdalghani** [comment] 2019-07-08 16:28
![image](https://user-images.githubusercontent.com/33901325/60826274-c64f2300-a1ad-11e9-958a-27f5dc3239e9.png)
The changes in the .bat file worked. However, the metro bundler takes too long to load the dependency graph and then the app crashes in the emulator as soon as the BUNDLE process reaches 100%

**Comment by thymikee** [comment] 2019-07-08 16:42
@naderabdalghani I suppose you use Node >=12.5, please downgrade to 12.4. See https://github.com/react-native-community/cli/issues/485#issuecomment-509210382

**Comment by naderabdalghani** [comment] 2019-07-08 17:31
Memory usage has significantly improved after downgrading to node 12.4.0. However, the app still crashes after BUNDLE process reaches 100% or I manually open it
![image](https://user-images.githubusercontent.com/33901325/60830235-08309700-a1b7-11e9-944c-a7c445461885.png)

**Comment by thymikee** [comment] 2019-07-08 17:36
@naderabdalghani That's different issue, likely caused by configuration in your app. Please try a new project with a set of libraries you use and try to find the bug. If you're then sure it's something inside React Native or CLI, please file an issue accordingly.

**Comment by skrypak** [comment] 2019-07-09 07:32
It's the same error on Ubuntu 16.04

**Comment by DaviRJ** [comment] 2019-07-11 00:03
Same error on Linux (Elementary OS). 
For a temporary fix, [this](https://github.com/react-native-community/cli/issues/484#issuecomment-508913679) works fine.

**Comment by arryanggaputra** [comment] 2019-07-11 06:19
Metro cannot start, so I run `react-native start` then I got this error, anyone know how to fix this?
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: UNKNOWN: unknown error, lstat 'D:\WarungPintar\kurir-app\node_modules\.bin\JSONStream'
Emitted 'error' event at:
    at NodeWatcher.checkedEmitError (D:\WarungPintar\kurir-app\node_modules\metro\node_modules\sane\src\node_watcher.js:143:12)
    at Walker.emit (events.js:198:13)
    at D:\WarungPintar\kurir-app\node_modules\walker\lib\walker.js:52:12
    at D:\WarungPintar\kurir-app\node_modules\graceful-fs\polyfills.js:282:31
    at FSReqWrap.oncomplete (fs.js:153:21)
```

**Comment by abhirup03** [comment] 2019-08-23 05:15
I have recently upgraded to RN 0.60.0 from 0.57, after running "**react-native run-android**" the configurations from build.grade executes successfully. But the metro bundler launches and doesn't loads and says it's done. The app crashes, as the metro bundler doesn't run. 

Any approach to fix this?  @thymikee 
![Screen Shot 2019-08-23 at 10 43 46 AM](https://user-images.githubusercontent.com/33601838/63568515-15e98280-c593-11e9-9f12-6eb716eabed4.png)

**Comment by thymikee** [comment] 2019-08-23 07:45
Does running `react-native start` first help? Also, if you use Node 12, make sure to upgrade to 12.9+, there was a bug in V8 that affected Metro.

**Comment by GaetanB999** [comment] 2019-08-23 12:32
Same issue here.

System:
    OS: macOS 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 2.19 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

as a workaround, it's works when I do "yarn start" first (or npm start)

**Comment by abhirup03** [comment] 2019-08-25 09:50
@thymikee trying out that I got the following errors: 
![Screen Shot 2019-08-25 at 3 19 46 PM](https://user-images.githubusercontent.com/33601838/63648318-e336ba00-c74b-11e9-9440-8c4cef8ec239.png)

**Comment by abhirup03** [comment] 2019-08-25 19:48
My system's node version is : 12.9.0 @thymikee

**Comment by abhirup03** [comment] 2019-08-26 04:26
Did anyone face a same issue? Any particular approach to follow and fix this? Please kindly update.

**Comment by thymikee** [comment] 2019-08-26 05:24
Did you actually read the error message? The registry is down for some reason and it cannot download Android deps. It's not related to Metro anyhow.

**Comment by abhirup03** [comment] 2019-08-26 05:36
Hi @thymikee  I encountered that yesterday and tried making few changes. Now, as you can see in the picture below the build is successful, but the metro bundler doesn't load. 
![Screen Shot 2019-08-26 at 11 01 15 AM](https://user-images.githubusercontent.com/33601838/63667469-85f54400-c7f1-11e9-9839-d1fb03492c22.png)

**Comment by thymikee** [comment] 2019-08-26 06:28
Looks like Metro is running fine (see the "Loading dependency graph, done." message). It's possible that your app is not able to connect to it. See https://stackoverflow.com/questions/42064283/react-nativecould-not-connect-to-development-server-on-android or similar.

**Comment by JindalPrashant** [comment] 2019-11-15 18:39
I was using node 12.13.0 and facing the same issue. Now I downgraded it to 10.15.0 and metro bundle is running without fail.

**Comment by JindalPrashant** [comment] 2019-11-15 18:40
> @naderabdalghani I suppose you use Node >=12.5, please downgrade to 12.4. See [#485 (comment)](https://github.com/react-native-community/cli/issues/485#issuecomment-509210382)

It worked for me.

**Comment by rbalaga** [comment] 2019-11-20 16:28
> > @naderabdalghani I suppose you use Node >=12.5, please downgrade to 12.4. See [#485 (comment)](https://github.com/react-native-community/cli/issues/485#issuecomment-509210382)
> 
> It worked for me. Thanks

Thanks It worked for me. running 13.1.0 not worked. downgraded to 12.4.0 and it worked. :)

**Comment by gBusato** [comment] 2019-11-23 09:54
I also downgraded to 12.4.0 and it worked 

If you are using chocolatey on windows 

`choco uninstall nodejs`
then 
`choco install nodejs --version 12.4.0`

**Comment by pjunior94** [comment] 2019-11-23 13:02
Same here, downgrading node from v12.13.1 to 12.4.0 to work

**Comment by HosseinAlipour** [comment] 2019-11-28 11:19
I have the same issue with version 3.0.4, which is the latest right now, should I open a new issue?

**Comment by felrugai** [comment] 2019-12-03 17:33
> I also downgraded to 12.4.0 and it worked
> 
> If you are using chocolatey on windows
> 
> `choco uninstall nodejs`
> then
> `choco install nodejs --version 12.4.0`

Confirmed that it's working aswell.

**Comment by samdsg** [comment] 2020-01-01 16:57
> @zenz it's not about rmeoving the file, but doing this diff:
> 
> ```diff
> -node "%~dp0..\cli.js" --projectRoot ../../../ start
> +node "%~dp0..\cli.js" start
> ```

where can i find the file to modify

**Comment by Pk1631037** [comment] 2020-01-05 14:30
nodemodules/react-native/scripts/launchPackager.bat

**Comment by cvallejoec** [comment] 2020-01-14 00:00
Actually, this work for me.
https://github.com/expo/expo-cli/issues/1074#issuecomment-546167583

**Comment by MAsad-Nawaz** [comment] 2020-02-04 04:52
> ## Environment
> ```
> System:
>     OS: Windows 10
>     CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
>     Memory: 8.99 GB / 15.89 GB
>   Binaries:
>     Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>     npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
>   SDKs:
>     Android SDK:
>       Android NDK: 18.1.5063045
>   IDEs:
>     Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788
> ```
> 
> ```
> react-native-cli: 2.0.1
> react-native: 0.60.0
> ```
> 
> ## Description
> Doing `yarn react-native run-android` opens the `metro bundler` but it immediately closes. Don't know if its a bug with the `cli` or the `metro` itself. This only happens on Windows, I think.
> 
> Things I have tried:
> 
> 1. Restarting my system
> 2. Clearing cache etc.
> 
> ## Reproducible Demo
> 1. Create a new project using `react-native init`
> 2. Run `yarn react-native run-android`

Open Your Project Folder in IDE like Visual Studio Code etc

Click on node_modules folder

Click on metro-config folder

Click on src folder

Click on default folder

Open blacklist.js file and replace the following code
`var sharedBlacklist = [
/node_modules[/\\]react[/\\]dist[/\\].*/,
/website\/node_modules\/.*/,
/heapCapture\/bundle\.js/,
/.*\/__tests__\/.*/
];`
With
`var sharedBlacklist = [
/node_modules[\/\\]react[\/\\]dist[\/\\].*/,
/website\/node_modules\/.*/,
/heapCapture\/bundle\.js/,
/.*\/__tests__\/.*/
];`

**Comment by aamir-munir** [comment] 2020-05-19 08:43
guys any other solution?
I tried everything but my bundler close immediately and unable to run the app. it was working fine but I just reinstall window and below is the configuration:

System:
    OS: Windows 10
    Binaries:
    Node: 12.4.0
    npm: 6.9.0 
react-native-cli: 2.0.1
react-native: 0.58.3

I really need this fix. Any quick help would appreciate it

**Comment by netgfx** [comment] 2020-10-28 07:18
What is the status of this? I'm still experiencing this error, the metro bundle closing with running `react-native run-android` on node `12.9.1`

**Comment by whatdtech** [comment] 2020-10-31 09:18
In my case I intentionally uninstalled app from emulator and faced the issue. Tried all options but changing app name is the best option. Else reinstall android studio with a new emulator.

**Comment by whatdtech** [comment] 2020-10-31 09:20
Try changing app name in app.Json, build.gradle, AndroidManifest.xml in both debug and main folders

**Comment by engineerbaraazakariya** [comment] 2020-12-09 18:31
In mac env I also had the same issue and the solution was: 
`brew install nvm && brew unlink node && nvm install v10.23.0 && nvm use v10.23.0 && nvm alias default v10.23.0`
then `react-native run-android` worked like a charm no single error.

**Comment by charleston10** [comment] 2021-06-22 18:22
> > ## Environment
> > ```
> > System:
> >     OS: Windows 10
> >     CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
> >     Memory: 8.99 GB / 15.89 GB
> >   Binaries:
> >     Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
> >     Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
> >     npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
> >   SDKs:
> >     Android SDK:
> >       Android NDK: 18.1.5063045
> >   IDEs:
> >     Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788
> > ```
> > 
> > 
> > ```
> > react-native-cli: 2.0.1
> > react-native: 0.60.0
> > ```
> > 
> > 
> > ## Description
> > Doing `yarn react-native run-android` opens the `metro bundler` but it immediately closes. Don't know if its a bug with the `cli` or the `metro` itself. This only happens on Windows, I think.
> > Things I have tried:
> > 
> > 1. Restarting my system
> > 2. Clearing cache etc.
> > 
> > ## Reproducible Demo
> > 
> > 1. Create a new project using `react-native init`
> > 2. Run `yarn react-native run-android`
> 
> Open Your Project Folder in IDE like Visual Studio Code etc
> 
> Click on node_modules folder
> 
> Click on metro-config folder
> 
> Click on src folder
> 
> Click on default folder
> 
> Open blacklist.js file and replace the following code
> `var sharedBlacklist = [ /node_modules[/\\]react[/\\]dist[/\\].*/, /website\/node_modules\/.*/, /heapCapture\/bundle\.js/, /.*\/__tests__\/.*/ ];`
> With
> `var sharedBlacklist = [ /node_modules[\/\\]react[\/\\]dist[\/\\].*/, /website\/node_modules\/.*/, /heapCapture\/bundle\.js/, /.*\/__tests__\/.*/ ];`

I'm using node v16.3.0 and this adjustment you posted made it work.. tks

**Comment by cparello** [comment] 2021-11-05 18:40
i always this same problem and the error is usually some file in node_modules was unavailable, if i just continue to press play from android studio it eventually works but sometimes it takes up to 10 tries. any ideas ?

**Comment by netgfx** [comment] 2021-11-05 20:47
@cparello Switch to Flutter for 100% guaranteed builds, Android and iOS, every single time!

I got bored to fight the compiler, did the switch and never looked back!

**Comment by SourceCipher** [comment] 2022-07-14 17:05
How is this still an issue? Its such a waste of time to compile the code from like 15th time because the metro keeps exiting when the build is at 95-99%. I updated the package but not fixed, tried various fixes from the comments above - nothing.

**Comment by jmmwangi007** [comment] 2022-08-09 08:35
I'm not too sure if this is the correct solution but opening an new console and running

`npx react-native start`

works for me.

**Comment by SamAlexMunro** [comment] 2022-09-27 17:01
Why is this matter closed? 

This is still an issue with the latest version of React Native on a fresh project.

**Comment by khadeshyam** [comment] 2023-01-30 13:37
I had the same issue.The Metro runs on port 8081.But something else running was running on the port.I resolved by killing that process.refer https://reactnative.dev/docs/troubleshooting for more info

**Comment by MattNic2** [comment] 2023-07-20 00:59
Was a permanent fix ever found for this problem, I'm still experiencing it. 
RN version : 0.71.8
RN CLI version: 2.0.1

**Comment by szymonrybczak** [comment] 2023-07-20 05:46
Hey @MattNic2, mind upgarding to the latest version of RN? We fixed few things around starting packager in `run-android`.

**Comment by bertdida** [comment] 2023-08-10 15:35
For me, quitting the Docker solves my issue.
