### ISSUE TITLE
Regression: Cannot connect to packager via IP or physical ios devices

### ISSUE THREAD

**Issue by cpojer** [react-native-community/cli#324] opened 2019-04-17 08:42 UTC
* * *
  This issue was originally created by @FrikkieSnyman as facebook/react-native#24002.
  * * *

  ## 💥 Regression Report
Upgraded to RN 0.59.0, and tried to run my app on ios. When I tried to enable remote debugging, I got an error saying that the connection to http://localhost:8081/debugger-proxy?role=client timed out. 

I followed the troubleshooting here: http://facebook.github.io/react-native/docs/running-on-device.html#troubleshooting, and confirmed that my local machine's IP address is being detected correctly. 

I then tried opening the debugger-ui on chrome by navigating to my local ip (ie 10.27.79.224:8081/debugger-ui) and it failed to connect. This definitely worked in RN 0.57 (from which I upgraded). Testing on RN 0.58.6, this also works.

## Last working version

Worked up to version: 0.58.6

Stopped working in version: 0.59.0

## To Reproduce

Install React Native version 0.59.0. Run `npm start` to start the packager. Obtain the local machine's IP, and then navigate to the obtained IP:8081/debugger-ui. Connection should be refused, and debugging on a physical ios device is not possible.

## Expected Behavior

I expect to be able to debug remotely from a physical ios device.

## Code Example
n/a

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 432.55 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v8.15.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 27.0.3, 28.0.3
        API Levels: 23, 26, 27, 28
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.3.14 => 16.3.14 
      @types/react-native: 0.57.11 => 0.57.11 
      react: 16.8.4 => 16.8.4 
      react-native: 0.59.0 => 0.59.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by FrikkieSnyman** [comment] 2019-05-21 07:29
Any progress on this?

**Comment by thymikee** [comment] 2019-05-21 07:44
AFAIK nobody is currently working on this. The blocker for us internally was that we couldn't find a reliable way to test the `start` command locally after migration to monorepo. Thankfully we've recently found a way to do it, so if anybody is interested in investigating this, please use one of these commands:

```sh
# when @react-native-community/cli is `yarn link`ed
REACT_NATIVE_APP_ROOT=/path/to/react-native-cli yarn react-native start
# or when it's not
REACT_NATIVE_APP_ROOT=/path/to/react-native-cli node /path/to/react-native-cli/packages/cli/build start
```

The `REACT_NATIVE_APP_ROOT` flag lets Metro resolve local paths inside this directory.

@FrikkieSnyman would you like to give it a shot?

**Comment by tientruongvan1995** [comment] 2019-09-06 00:57
yeah still getting this in RN 0.60.5. I updated from 0.58.5 and everything's corrupted :'(

**Comment by MrLoh** [comment] 2019-12-16 17:16
Hi, I realize this is just an open source project. But this bug has been lying around since April, and its about a broken core functionality (debugging on an iOS device). It's also not something someone who is new to this repo can easily tackle with a PR. I am really surprised there hasn't been more traction on this issue, as I imagine every react native developer must run into it. @grabbou you had mentioned in April that you were looking into it. Is there any chance this issue will get tackled, or is there any known workaround. Or anything one ca do to help to get this fixed.

**Comment by grabbou** [comment] 2020-03-19 14:16
Unfortunately, I can't reproduce this issue anymore. Everything works fine on the latest React Native (0.61).

I tested by turning on Chrome Debugger, accessing it from both the localhost and my phone (via IP address).

I am going to close this issue for now and in case you are still experiencing this, please comment and I will reopen and look into why this is happening.

**Closed by grabbou** 2020-03-19 14:16 UTC
Labels: Impact: Regression, bug, platform: ios, 📦Bundler

**Comment by MrLoh** [comment] 2020-03-19 16:27
@grabbou I still cannot get it to work on 61.5 but maybe just what needs to be configured changed. What did you do to access the Bundler from your phone, I am looking at the trouble shooting instructions [here](https://reactnative.dev/docs/running-on-device#2-ip-address) but there is no output containing `xip.io`. Probably the problem has to do with some change in macOS rather than RN.

**Comment by grabbou** [comment] 2020-03-20 08:36
I just looked up the IP address of my device and typed http://10.0.1.2:8081
and Packager status appeared on screen.
