### ISSUE TITLE
Error: Cannot find module 'D:\MyDev\rn_partage_mandats_v3\node_modules\react-native\cli.js'

### ISSUE THREAD

**Issue by khaledBou** [react-native-community/cli#1127] opened 2020-04-23 08:53 UTC
## Environment

System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 15.49 GB / 23.88 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
## Description

I tried to create a new react-native project using the command :
react-native init project
I got this error : 
Error: Cannot find module 'D:\MyDev\rn_partage_mandats_v3\node_modules\react-native\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at run (C:\Users\bouss\AppData\Roaming\npm\node_modules\react-native-cli\index.js:301:9)
    at createProject (C:\Users\bouss\AppData\Roaming\npm\node_modules\react-native-cli\index.js:249:3)
    at init (C:\Users\bouss\AppData\Roaming\npm\node_modules\react-native-cli\index.js:200:5)
    at Object.<anonymous> (C:\Users\bouss\AppData\Roaming\npm\node_modules\react-native-cli\index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

## Reproducible Demo

react-native init project

**Comment by thymikee** [comment] 2020-04-23 11:27
The latest version of react-native is 0.62. Can you try a it once again with 
```
npx --ignore-existing react-native init Project
```
Closing until then

**Comment by khaledBou** [comment] 2020-04-23 11:50
i got : 
error Error: Couldn't find the "C:\Users\bouss\AppData\Local\Temp\rncli-init-template-Ofj4Kl\node_modules\react-native\template.config.js file inside "react-native" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template

**Comment by thymikee** [comment] 2020-04-23 12:10
That's interesting, we fixed this bug recently. What's output when you run `npx --ignore-existing react-native --version`?

**Comment by khaledBou** [comment] 2020-04-23 12:25
i got 4.7.0

**Comment by thymikee** [comment] 2020-04-23 12:29
Ok, I'll reopen this and wait for someone to reproduce, because I'm not able to.

**Comment by khaledBou** [comment] 2020-04-23 12:30
okay thanks

**Comment by thymikee** [comment] 2020-04-23 12:33
Or else, let's close this as a duplicate of https://github.com/react-native-community/cli/issues/1121, we get a few of these issues. 

For `Couldn't find the "C:\Users\bouss\AppData\Local\Temp\rncli-init-template-Ofj4Kl\node_modules\react-native\template.config.js` can you check this issue please: https://github.com/react-native-community/cli/issues/733 and try to investigate?

**Closed by thymikee** 2020-04-23 12:33 UTC
Labels: env: windows

**Comment by khaledBou** [comment] 2020-04-23 12:54
okay i'm trying but still got the same error even after apply #733

**Comment by creator-jay** [comment] 2021-04-09 08:56
you can simply use npm install
