### ISSUE TITLE
Android Release Build (APK) with New Architecture

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [react-native-community/cli#2010] opened 2023-07-10 15:11 UTC
Hi, before migrating to new architecture we were able to use `./gradlew assembleRelease` to create release APK, but now we have below options:
1. ./gradlew bundleRelease && ./gradlew assembleRelease
2. npx react-native run-android --mode release

The problem with 2nd approach is it creates heavier apk size(65.x mb) as compared to first approach(62.x mb) and it also looks for connected device to run the APK created.

I just wanted to know if there is any command with to just create the APK with react-native like `npx react-native build-android --mode=release` (which create aab file) or if there is option we can use to change the output file as APK instead aab.

**Comment by szymonrybczak** [comment] 2023-07-11 07:43
Hello 👋, you can do `npx react-native build-android --tasks assembleRelease`

**Comment by ravindraguptacapgemini** [comment] 2023-07-11 08:15
@szymonrybczak no it did not work bro, getting the same issue mentioned in https://github.com/facebook/react-native/issues/38237

**Comment by szymonrybczak** [comment] 2023-07-11 08:28
> Also this command tries to start metro bundler, which is not required.

For this we have `--no-packager` flag.

If you're able to create demo where we can reproduce this error, please do it 🙏 It will help us a lot in looking for cause of the problem. Because after reading this issue and https://github.com/facebook/react-native/issues/38237 I can't say anything specific.

**Comment by szymonrybczak** [comment] 2023-07-17 06:46
@ravindraguptacapgemini so are you able to create reproducible demo? :)

**Comment by adamTrz** [comment] 2023-09-05 11:41
Closing the issue but more than happy to reopen if OP is still struggling with it

**Closed by adamTrz** 2023-09-05 11:41 UTC
Labels: question

**Comment by heithemkacem** [comment] 2024-06-20 13:13
same problem here

**Comment by YowaiCoder** [comment] 2025-06-10 03:41
Same issue here.

```json
"react-native": "0.79.2"
"@react-native-community/cli": "18.0.0"
```
