### ISSUE TITLE
CLI: unexpected token '?'

### ISSUE THREAD

**Issue by harrymash2006** [react-native-community/cli#1703] opened 2022-09-23 12:40 UTC
### Description

Hi guys,

just created a new project and it is throwing this error when doing archive on iOS and when doing build on Android

Showing Recent Messages
+ /usr/local/bin/node /Users/hardik/Documents/GitHub/ReactNApp/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/hardik/Library/Developer/Xcode/DerivedData/ArcedirovNew-cdkamivgjmneqpgzgxxedswjccki/Build/Intermediates.noindex/ArchiveIntermediates/ReactNApp/BuildProductsPath/Release-iphoneos/main.jsbundle --assets-dest /Users/hardik/Library/Developer/Xcode/DerivedData/ReactNApp-cdkamivgjmneqpgzgxxedswjccki/Build/Intermediates.noindex/ArchiveIntermediates/ArcedirovNew/BuildProductsPath/Release-iphoneos/ArcedirovNew.app

/Users/hardik/Documents/GitHub/ReactNApp/node_modules/@react-native-community/cli/build/index.js:156

    cmd.option(opt.name, opt.description ?? '', opt.parse || (val => val), typeof opt.default === 'function' ? opt.default(rest[0]) : opt.default);

Please advice how to fix this. thanks

### Version

0.70.1

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 365.09 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.02.28.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Android TV Intel x86 Atom, android-24 | Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64, android-N | Android Wear ARM EABI v7a, android-N | Android Wear Intel x86 Atom, android-N | Intel x86 Atom, android-N | Intel x86 Atom_64
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Trying to build on Android 
Archive on iOS for app store upload

### Snack, code example, screenshot, or link to a repository

https://pasteboard.co/jF639A0h1o6b.png

**Comment by cortinico** [comment] 2022-09-23 13:41
Here the correspondig issue on React Native: https://github.com/facebook/react-native/issues/34768 Let's close both once this is sorted out

**Comment by mantegnous** [comment] 2022-09-23 14:01
same bug after updating to react 0.70.1 from 0.67.4

if i do npx react-native info, the cmd return me: Unexpected token '?'

**Comment by harrymash2006** [comment] 2022-09-26 14:09
@cortinico @jsierles @sharnik Is there any patch available for this fix? or can I use some alpha version which fixes this issue ?

**Comment by mantegnous** [comment] 2022-09-26 16:16
Update note js to 16 resolve this problem

**Comment by cortinico** [comment] 2022-09-27 14:22
> @cortinico @jsierles @sharnik Is there any patch available for this fix? or can I use some alpha version which fixes this issue ?

As suggested, it seems like the issue is with your Node version.

**Comment by adamTrz** [comment] 2022-09-30 09:25
Hi @harrymash2006  @mantegnous - have you tried steps suggested here https://github.com/facebook/react-native/issues/34768 ? (remove old system-wide `node` and use latest? )

**Comment by harrymash2006** [comment] 2022-10-03 15:39
Still getting the same issue @adamTrz when doing archive of iOS build. It is still referring to /usr/local/bin/mode even after changing the system node pointing to NVM installed path.

![error](https://user-images.githubusercontent.com/5957516/193619057-544480b3-11bd-4660-8c16-73037a5995d6.jpg)

**Comment by liamjones** [comment] 2022-10-04 08:59
@harrymash2006 you're on 0.70.1 so you should be able to edit your `ios/.xcode.env` (or make an `ios/.xcode.env.local`) to override how it finds the node version to use

**Comment by adamTrz** [comment] 2022-10-14 09:24
Hi @harrymash2006 have you tried the fixed mentioned above? 
I'll close the issue for now but feel free to reopen if you still encounter problems when running the cli commands.

**Closed by adamTrz** 2022-10-14 09:24 UTC
Labels: bug report

**Comment by laksithakumara-cb** [comment] 2023-01-10 06:56
Hello,

This problem still exists. im using node version v19.4.0 and React Native 0.70.1

![ssss](https://user-images.githubusercontent.com/86996291/211482391-225e19d8-0b48-4e78-9cc8-537aacdbc8d5.jpg)

**Comment by liamjones** [comment] 2023-01-10 10:21
@laksithakumara-cb `/usr/local/bin/node -v` says 19.4 too? Your screenshot just shows you doing `node -v` which could potentially be a different path.

**Comment by laksithakumara-cb** [comment] 2023-01-10 10:31
yes, that path also shows the same version. enable to upload new builds(Xcode failed because of this error) because of this error.


Downgraded to node 16 and the problem was solved.

**Comment by Digiraf** [comment] 2023-08-18 06:31
set default node version with nvm:
`nvm alias default 16`
restart xcode/android studio
