### ISSUE TITLE
Text must not be null or empty

### ISSUE THREAD

**Issue by ldco2016** [react-native-community/cli#744] opened 2019-09-23 21:00 UTC
## Environment

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 2.53 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 2.9.0 => 2.9.0
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Description

When we try to run a build in Azure DevOps, specifically to generate apks, we get the following error:

```
FAILURE: Build failed with an exception.
 
* Where:
Script '/Users/vsts/agent/2.155.1/work/1/s/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 191
 
* What went wrong:
A problem occurred evaluating settings 'NFIBEngage'.
> Text must not be null or empty
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

That line 191 is in reference so this line of code here:

`def json = new JsonSlurper().parseText(reactNativeConfigOutput)`

I do have the latest version of `@react-native-community/cli` in my `package-lock.json` file:

```
"@react-native-community/cli": {
      "version": "2.9.0",
      "resolved": "https://registry.npmjs.org/@react-native-community/cli/-/cli-2.9.0.tgz",
      "integrity": "sha512-6TYkrR1pwIEPpiPZnOYscCGr5Xh8RijqBPVAOGTaEdpQQpc/J7GDPrePwbyTzwmCPtiK6XT+T5+1AiAK5bz/sw==",
      "requires": {
        "@hapi/joi": "^15.0.3",
        "@react-native-community/cli-platform-android": "^2.9.0",
        "@react-native-community/cli-platform-ios": "^2.9.0",
        "@react-native-community/cli-tools": "^2.8.3",
        "chalk": "^2.4.2",
        "commander": "^2.19.0",
        "compression": "^1.7.1",
        "connect": "^3.6.5",
        "cosmiconfig": "^5.1.0",
        "deepmerge": "^3.2.0",
        "envinfo": "^7.1.0",
        "errorhandler": "^1.5.0",
        "execa": "^1.0.0",
        "fs-extra": "^7.0.1",
        "glob": "^7.1.1",
        "graceful-fs": "^4.1.3",
        "inquirer": "^3.0.6",
        "lodash": "^4.17.5",
        "metro": "^0.54.1",
        "metro-config": "^0.54.1",
        "metro-core": "^0.54.1",
        "metro-react-native-babel-transformer": "^0.54.1",
        "minimist": "^1.2.0",
        "mkdirp": "^0.5.1",
        "morgan": "^1.9.0",
        "node-notifier": "^5.2.1",
        "open": "^6.2.0",
        "ora": "^3.4.0",
        "plist": "^3.0.0",
        "semver": "^5.0.3",
        "serve-static": "^1.13.1",
        "shell-quote": "1.6.1",
        "ws": "^1.1.0"
      }
    },
    "@react-native-community/cli-platform-android": {
      "version": "2.9.0",
      "resolved": "https://registry.npmjs.org/@react-native-community/cli-platform-android/-/cli-platform-android-2.9.0.tgz",
      "integrity": "sha512-VEQs4Q6R5tnlYFrQIFoPEWjLc43whRHC9HeH+idbFymwDqysLVUffQbb9D6PJUj+C/AvrDhBhU6S3tDjGbSsag==",
      "requires": {
        "@react-native-community/cli-tools": "^2.8.3",
        "chalk": "^2.4.2",
        "execa": "^1.0.0",
        "jetifier": "^1.6.2",
        "logkitty": "^0.6.0",
        "slash": "^3.0.0",
        "xmldoc": "^1.1.2"
      }
    },
    "@react-native-community/cli-platform-ios": {
      "version": "2.9.0",
      "resolved": "https://registry.npmjs.org/@react-native-community/cli-platform-ios/-/cli-platform-ios-2.9.0.tgz",
      "integrity": "sha512-vg6EOamtFaaQ02FiWu+jzJTfeTJ0OVjJSAoR2rhJKNye6RgJLoQlfp0Hg3waF6XrO72a7afYZsPdKSlN3ewlHg==",
      "requires": {
        "@react-native-community/cli-tools": "^2.8.3",
        "chalk": "^2.4.2",
        "xcode": "^2.0.0"
      }
    },
```

## Reproducible Demo

You can use this copy to attempt to reproduce:
https://www.dropbox.com/s/eeo46lg93ndv5ou/Xcode_IN.zip?dl=0

And in-lieu of an Azure DevOps handy you can run this command in terminal:

`npm run setup && cd android && ./gradlew assembleDevRelease`

The above command should get you the same error.

**Comment by sebastos01** [comment] 2019-10-04 11:29
Got the same issue, works on local system but not in Jenkins.

**Comment by grabbou** [comment] 2019-10-10 17:41
Duplicate of #624

**Closed by grabbou** 2019-10-10 17:41 UTC
Labels: bug report
