### ISSUE TITLE
Cannot update React-native

### ISSUE THREAD

**Issue by Freir96** [react-native-community/cli#815] opened 2019-10-19 13:04 UTC
## Environment

react-native -v
react-native-cli: 2.0.1
react-native: 0.59.10

npm -v 6.12.0

node -v v10.16.0

## Description

After using react-native upgrade, as suggested in https://facebook.github.io/react-native/docs/0.60/upgrading I got:

info No version passed. Fetching latest... info Fetching diff between v0.59.10 and v0.61.2... error Failed to fetch diff for react-native@0.61.2. Maybe it's not released yet? info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#version-changes

Changing to a specific version (react-native upgrade 0.61.0-rc.0) do not help.

## Reproducible Demo
From react-native: 0.59.10 run commend 'react-native upgrade'

**Comment by thymikee** [comment] 2019-10-21 09:27
Duplicate of https://github.com/react-native-community/cli/issues/707 and many others

**Closed by thymikee** 2019-10-21 09:27 UTC
Labels: bug report
