### ISSUE TITLE
Unsupported class file major version 63

### ISSUE THREAD

**Issue by abdulrhman-alfeel** [react-native-community/cli#1719] opened 2022-10-16 15:39 UTC
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'D:\project\tools\prouprint\android\settings.gradle' (D:\project\tools\gradle-7.5.1\caches\7.5.1\scripts\5o6jmz0o7vlzhu5xtvutuo3me).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 772ms

**Comment by cortinico** [comment] 2022-10-17 11:02
There seems to be somethign going on with your Java version. Which version of Java are you using (you should be able to see it with `java -version`).

**Comment by adamTrz** [comment] 2022-10-21 08:46
@abdulrhman-alfeel any news on the issue? Have you checked you Java version?

**Comment by BenMakesGames** [comment] 2022-10-22 13:38
I'm receiving this error as well.

```
* Where:
Settings file 'D:\Development\Mobile\GuessMyWeight\platforms\tempPlugin\core\settings.gradle'

* What went wrong:
Could not compile settings file 'D:\Development\Mobile\GuessMyWeight\platforms\tempPlugin\core\settings.gradle'.
```

`java --version` reports:

```
openjdk 19.0.1 2022-10-18
OpenJDK Runtime Environment (build 19.0.1+10-21)
OpenJDK 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)
```

**Comment by abdulrhman-alfeel** [comment] 2022-10-23 19:49
Use jdk-17.0.4

**Comment by abdulrhman-alfeel** [comment] 2022-10-23 19:51
I use jdk-17.0.4 and it is installed and there is no problem. How do I know if the problem is caused by it?

**Comment by abdulrhman-alfeel** [comment] 2022-10-23 20:09
Excuse me, I only receive repository messages to email and I only open it often

**Comment by behzodfaiziev** [comment] 2023-01-15 23:51
> I use jdk-17.0.4 and it is installed and there is no problem. How do I know if the problem is caused by it?

The problem is that version 19 is not supported. Btw, I am a Flutter developer and version 19(63) was working fine before updating some packages(dependencies)

**Comment by UNIDY2002** [comment] 2023-01-19 01:26
From my personal experience, react-native is supporting JDK19 perfectly now.

You should [upgrade gradle to 7.6](https://docs.gradle.org/7.6/release-notes.html), which added support for Java 19 and was released in Nov 2022.

**Comment by cortinico** [comment] 2023-01-19 09:15
> From my personal experience, react-native is supporting JDK19 perfectly now.

Yup that's the case right now (with RN 0.71), but it was not the case when this issue was opened.

**Comment by JSBCompuCal** [comment] 2023-01-19 10:30
Hello, I'm having the same problem. I'm using JDK 19 and I get the major version 63 problem. If I use JDK 17 I get major version 61problem. I'm using gradle 7.6 manually installed because it didn't pick it up from android studio. Any ideas how to solve this?
![image](https://user-images.githubusercontent.com/123072744/213418867-96f56f95-c9e2-435a-8664-62c07f25584e.png)
![image](https://user-images.githubusercontent.com/123072744/213419024-434d40b2-7fc0-4252-8474-cd53b00af281.png)

**Comment by JSBCompuCal** [comment] 2023-01-19 11:13
Ok, I gave up and tried to install react native instead. While trying to install react native I had to install JDK 11 with chocolatey and after that apache cordova started working. The installation with chocolatey (that is optianlly installed when you install nodejs) of JDK11 also adds it to your path and enviromental variables, so I highly recommend to use the react native installation up till the point where you install the JDK 11 and then keep going with whichever you want (Cordova or React)

**Comment by Usaid-Dev** [comment] 2023-01-21 07:57
I finally found the solution soo just go at your project folder and then open android/gradle/wrapper/gradle-wrapper-properties then change this :- distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip To This :- distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-all.zip and then your issue get solved 😁

**Comment by mensur-durakovic** [comment] 2023-01-24 19:48
@Usaid-Dev thank you, solved my problem with fluttertoast package.

**Comment by wa-lopezch** [comment] 2023-01-25 17:54
Usaid-Dev   ¿Que version de java estas utilizando? y que te funciono para solucionar el problema con gradle 7.6? gracias..

**Comment by Usaid-Dev** [comment] 2023-01-26 06:33
> Usaid-Dev ¿Que version de java estas utilizando? y que te funciono para solucionar el problema con gradle 7.6? gracias..

<img width="635" alt="Screenshot 2023-01-26 at 11 25 53 AM" src="https://user-images.githubusercontent.com/67046451/214771417-78ccdb5c-4043-4d72-8bba-6175cf57859a.png">

Estoy usando esta versión de Java y esta solución me ayuda a resolver este error: -

![IMG_0101](https://user-images.githubusercontent.com/67046451/214771673-b30d522b-1566-4caa-bc25-c277a754dac9.PNG)

**Comment by ta4h1r** [comment] 2023-01-26 06:49
I needed to downgrade to JDK 17 and then it worked fine

**Comment by k2xl** [comment] 2023-01-28 14:33
> 



> I finally found the solution soo just go at your project folder and then open android/gradle/wrapper/gradle-wrapper-properties then change this :- distributionUrl=https://services.gradle.org/distributions/gradle-7.4-all.zip To This :- distributionUrl=https://services.gradle.org/distributions/gradle-7.6-all.zip and then your issue get solved 😁

Worked for me too with expo / react-native . Also be mindful of extra whitespaces in the properties when pasting in this (otherwise you'll get another error - caused me a headache for a while)

**Comment by Imaginet1** [comment] 2023-02-06 15:52
I have the same issue but thanging the distributionURL value does not work for me.  When I run the build process, the value gets reset/overwritten back to the original value.  Any ideas how to stop this?

**Comment by joshuapinter** [comment] 2023-02-16 17:37
Seeing this after upgrading Gradle Plugin from 7.4.0 to 7.4.1. Using Java 19 and Gradle 7.6. 

7.4.0 showed no such issue and if I revert the upgrade the error goes away and the build works fine.

**Comment by danielxiin1124gmail** [comment] 2023-02-22 06:31
thanks

**Comment by jruizu** [comment] 2023-03-08 03:26
@Usaid-Dev Muchas gracias, funcionó para mi!

**Comment by tiagouy** [comment] 2023-03-09 13:58
> > 
> 
> @wa-lopezch :- estas utilizando? y que te funciono para solucionar el problema con gradle 7.6? gracias..
> 
> <img alt="Screenshot 2023-01-26 at 11 25 53 AM" width="635" src="https://user-images.githubusercontent.com/67046451/214771417-78ccdb5c-4043-4d72-8bba-6175cf57859a.png">
> 
> Estoy usando esta versión de Java y esta solución me ayuda a resolver este error: -
> 
> ![IMG_0101](https://user-images.githubusercontent.com/67046451/214772436-b0d57f4c-4df6-4dda-8d62-71439db2a471.jpeg)

me pasa lo mismo, quiero cambiar la version de java antes que cambiar el GRADLE que aparte como no usare mas firebase ni push, preciso que este???

**Comment by tiagouy** [comment] 2023-03-09 13:59
> I needed to downgrade to JDK 17 and then it worked fine

como se hace Downgrad? o como se cambia la version por defecto?

**Comment by bdytx5** [comment] 2023-04-04 16:03
> 

rocketship granted

**Comment by Foxomat** [comment] 2023-04-20 12:14
> Use jdk-17.0.4

I am not even using react... And yet, trying to find a solution for my problem with the Godot engine brought me here AND IT WORKED.

**Comment by xiaozhang0532** [comment] 2023-09-13 05:51
You could fix it by changing the 'gradle-wrapper.properties' file with the following line:
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-milestone-1-all.zip`

If that doesn't resolve the issue, try downgrading your Java version and ensure that it matches the compatible version listed in the link below:
[Compatibility Matrix](https://docs.gradle.org/current/userguide/compatibility.html)

**Comment by hmohammed** [comment] 2023-09-21 04:49
upgrading gradle with jdk 17 seems to resolve the issue

**Comment by Navicna** [comment] 2023-10-18 18:30
> I finally found the solution soo just go at your project folder and then open android/gradle/wrapper/gradle-wrapper-properties then change this :- distributionUrl=https://services.gradle.org/distributions/gradle-7.4-all.zip To This :- distributionUrl=https://services.gradle.org/distributions/gradle-7.6-all.zip and then your issue get solved 😁

You are the guy!!! Solved for me!

**Comment by rodolfogoulart** [comment] 2023-10-23 19:03
> You could fix it by changing the 'gradle-wrapper.properties' file with the following line: `distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-milestone-1-all.zip`
> 
> If that doesn't resolve the issue, try downgrading your Java version and ensure that it matches the compatible version listed in the link below: [Compatibility Matrix](https://docs.gradle.org/current/userguide/compatibility.html)

Awesome, this work for me!

**Comment by adamTrz** [comment] 2023-10-24 08:24
Closing issue since OP have found solution :-)

**Closed by adamTrz** 2023-10-24 08:24 UTC
Labels: question

**Comment by Shahabmustafa** [comment] 2023-10-27 20:13
go to android folder > gradle > gradle-wrapper.properties open this file and change distributionUrl

before : distributionUrl=https://services.gradle.org/distributions/gradle-7.4-all.zip

After : distributionUrl=https://services.gradle.org/distributions/gradle-7.6-all.zip

**Comment by bvedant** [comment] 2023-11-08 04:48
So I have to make this distributionUrl property change for each new Gradle project I create?
