### ISSUE TITLE
How does `react-native run-ios` determine the arguments when invoking `xcodebuild`?

### ISSUE THREAD

**Issue by nbokmans** [react-native-community/cli#1816] opened 2023-02-03 15:45 UTC
I'm running into an issue trying to run my React Native app after updating to 0.71.2. 

When using `react-native run-ios`, I see that a `xcodebuild` command is ran:
```
xcodebuild -workspace app.xcworkspace -configuration Debug -scheme app -destination id=714D33E1-C723-5040-A13C-7CE0C3FD5A5B"
```

This has worked fine for months however since this update it seems this destination UDID no longer exists. Resulting in xcodebuild failing:
```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 70. To debug build logs further, consider building your app with Xcode.app, by opening app.xcworkspace.
```

Building the app using Xcode works without problems, and it opens on the simulator I selected in Xcode.

My question is: where is this destination UDID coming from? I'm not passing anything, I've cleaned my build folders, I've updated Xcode to latest (14.2), I've cleared the DerivedData and simulators, I've manually changed the selected simulator in Xcode, yet this problem still persists.

Manually overriding the UDID using the `--udid` flag like so:
```
npx react-native run-ios --udid="ADC901D0-E79F-4632-88E3-20B274A09E35"
```
DOES work, however, this does not "update" the stored UDID, and when I try to go back to just `npx react-native run-ios`, it still invokes xcodebuild with the wrong/old UDID.

How can I reset this? How can I change the destination permanently without passing the --udid flag?
Any help would be greatly appreciated.

**Comment by szymonrybczak** [comment] 2023-02-06 10:59
Hey @nbokmans 👋 This issue seems to be duplicate of https://github.com/react-native-community/cli/issues/1807. We're working on this :)  cc. @adamTrz

**Closed** 2023-02-09 13:02 UTC
Labels: question
