### ISSUE TITLE
Execution failed for task ':app:buildCMakeDebug[x86]'

### ISSUE THREAD

**Issue by code-hasaki** [react-native-community/cli#2340] opened 2024-03-18 14:44 UTC
## Environment

info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.18363
  CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
  Memory: 7.93 GB / 15.87 GB
Binaries:
  Node:
    version: 20.11.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 4.1.1
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    Android NDK: 22.1.7171670
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Disabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.8.34511.84 (Visual Studio Community 2022)
Languages:
  Java: 17.0.10
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

## Description

![image](https://github.com/react-native-community/cli/assets/71576322/06ca9883-4545-4282-9b22-e82524529750)
Execution failed for task ':app:buildCMakeDebug[x86]'.
> Unable to delete file 'G:\Dev\ReactNative\AwesomeProject\android\app\build\intermediates\cxx\Debug\3w702xfp\obj\x86'

npx react-native@latest init AwesomeProject --skip-install
cd AwesomeProject
yarn install
yarn start
The project works well

delete AwesomeProject dir
npx react-native@latest init AwesomeProject --skip-install
open file "AwesomeProject/android/gradle.properties", change "newArchEnabled=false" to "newArchEnabled=true"
cd AwesomeProject
yarn install
yarn start
Execution failed for task ':app:buildCMakeDebug[x86]'.

**Comment by szymonrybczak** [comment] 2024-03-20 08:04
hey, i see that there's `Unable to delete file...` log warning, are you sure there are right permissions granted for right folders? just a random thought that it can cause an issue - @cortinico might help? :pray:

**Comment by cortinico** [comment] 2024-03-20 11:15
Closing as duplicate of https://github.com/facebook/react-native/issues/43544

**Closed by cortinico** 2024-03-20 11:15 UTC
Labels: bug report

**Comment by muhammad-kumail** [comment] 2024-11-10 09:25
I faced this issue when i upgrade my react native version from 0.75.2 to latest 0.76.1 using react native upgrade helper. I change `newArchEnabled=true` in android/gradle.properties according to docomentation there. I think this is causing issue i changed back to `newArchEnabled=false` and my project build successfully. I don't know the reason how it resolved, is anyone knows? kindly tell us.

**Comment by muzammil1244** [comment] 2024-11-11 12:55
> I faced this issue when i upgrade my react native version from 0.75.2 to latest 0.76.1 using react native upgrade helper. I change `newArchEnabled=true` in android/gradle.properties according to docomentation there. I think this is causing issue i changed back to `newArchEnabled=false` and my project build successfully. I don't know the reason how it resolved, is anyone knows? kindly tell us.

"Sir, I am facing the same issue. If you have solved it, please let me know."

**Comment by Iamfavur** [comment] 2024-11-14 22:14
> I faced this issue when i upgrade my react native version from 0.75.2 to latest 0.76.1 using react native upgrade helper. I change `newArchEnabled=true` in android/gradle.properties according to docomentation there. I think this is causing issue i changed back to `newArchEnabled=false` and my project build successfully. I don't know the reason how it resolved, is anyone knows? kindly tell us.

I did this and it worked for now but i don't think we are supposed to set it to false, cause then we won't be able to use the new architecture that RN 0.76 is built on properly... thats my thought
Anybody that have a better alternative should let us know, thank you.

**Comment by JesielPalacios** [comment] 2024-11-17 03:22
> ## Environment
> info Fetching system and libraries information... System: OS: Windows 10 10.0.18363 CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz Memory: 7.93 GB / 15.87 GB Binaries: Node: version: 20.11.1 path: C:\Program Files\nodejs\node.EXE Yarn: version: 4.1.1 path: C:\Program Files\nodejs\yarn.CMD npm: version: 10.2.4 path: C:\Program Files\nodejs\npm.CMD Watchman: Not Found SDKs: Android SDK: Android NDK: 22.1.7171670 Windows SDK: AllowDevelopmentWithoutDevLicense: Disabled AllowAllTrustedApps: Enabled Versions: - 10.0.18362.0 IDEs: Android Studio: Not Found Visual Studio: - 17.8.34511.84 (Visual Studio Community 2022) Languages: Java: 17.0.10 Ruby: Not Found npmPackages: "@react-native-community/cli": Not Found react: installed: 18.2.0 wanted: 18.2.0 react-native: installed: 0.73.6 wanted: 0.73.6 react-native-windows: Not Found npmGlobalPackages: "_react-native_": Not Found Android: hermesEnabled: true newArchEnabled: true iOS: hermesEnabled: Not found newArchEnabled: Not found
> 
> ## Description
> ![image](https://private-user-images.githubusercontent.com/71576322/313717980-06ca9883-4545-4282-9b22-e82524529750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MTM4NTcsIm5iZiI6MTczMTgxMzU1NywicGF0aCI6Ii83MTU3NjMyMi8zMTM3MTc5ODAtMDZjYTk4ODMtNDU0NS00MjgyLTliMjItZTgyNTI0NTI5NzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDAzMTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTFhMTg2NTFkZDgxYTFkNTczM2QzYjMyMzM0MzNhYmQzZmViNzI1YjZhNTIyZjk1YTZkODNiYzU2MTZiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L_umZJL2ky-zI21Mx4GQt5LWcvMTZWbgxtNJtvJebIw) Execution failed for task ':app:buildCMakeDebug[x86]'.
> 
> > Unable to delete file 'G:\Dev\ReactNative\AwesomeProject\android\app\build\intermediates\cxx\Debug\3w702xfp\obj\x86'
> 
> npx react-native@latest init AwesomeProject --skip-install cd AwesomeProject yarn install yarn start The project works well
> 
> delete AwesomeProject dir npx react-native@latest init AwesomeProject --skip-install open file "AwesomeProject/android/gradle.properties", change "newArchEnabled=false" to "newArchEnabled=true" cd AwesomeProject yarn install yarn start Execution failed for task ':app:buildCMakeDebug[x86]'.

-
-
-
-
-
-

This worked for me. But now it was already in true, so I changed it to false, then worked.

This situation was because I was installing reac navigation my app, I need to implement navigation between screens.

**Comment by hgq287** [comment] 2024-11-24 07:54
Solved. Please see at: https://stackoverflow.com/questions/78244859/i-got-execution-failed-for-task-appconfigurecmakedebugarm64-v8a-while-buil/79219605#79219605

**Comment by KishanSardhara** [comment] 2025-06-29 07:35
✅ Why did setting newArchEnabled=false fix it?
With newArchEnabled=false, React Native builds the app using the legacy architecture, which :-
Avoids TurboModules
Skips Fabric Renderer
Does not compile C++ JSI bindings
Builds faster and uses more stable Java-based modules
This means no native C++ linking → no linker errors → build success.

🛠️ When to use newArchEnabled=true
You should only enable it when:
You really need TurboModules or Fabric (e.g., performance gains, using latest libraries).

You’ve configured:
Correct NDK version (ideally NDK 25 or 26, not 27)
CMakeLists.txt and build.gradle with all required flags
C++ standard library linking (-lc++_shared)

Then you’re ready to deal with C++ toolchain debugging.
