### ISSUE TITLE
react-native doctor does not find installed Android Studio installed SDKs

### ISSUE THREAD

**Issue by tgroshon** [react-native-community/cli#1219] opened 2020-07-15 22:50 UTC
## Environment
```
System:
    OS: Linux 5.4 Pop!_OS 20.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.92 GB / 31.08 GB
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 10.19.0 - /tmp/yarn--1594853258033-0.9827053025900041/node
    Yarn: 1.22.4 - /tmp/yarn--1594853258033-0.9827053025900041/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
  Languages:
    Java: 11.0.7 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.63.1 => 0.63.1
  npmGlobalPackages:
    *react-native*: Not Found
```
## Description
On ubuntu based system with Android Studio configured and SDKs installed but running `react-native doctor` does not find any Android SDKs.

But running `react-native run-android` works

![Screenshot from 2020-07-15 18-25-50](https://user-images.githubusercontent.com/1794859/87607619-c096f200-c6cb-11ea-9e4e-30752f46a4a9.png)
![Screenshot from 2020-07-15 18-26-46](https://user-images.githubusercontent.com/1794859/87607624-c2f94c00-c6cb-11ea-9557-039024cfe38b.png)

## Reproducible Demo

:man_shrugging:

**Comment by SirMishaa** [comment] 2021-01-29 00:27
What about this ? I've the same issue

**Comment by Devorein** [comment] 2021-04-03 06:31
Please refer to this thread where the answer has been posted. [1220](https://github.com/react-native-community/cli/issues/1220)

**Comment by thymikee** [comment] 2021-04-03 07:04
Duplicate of #1220

**Closed by thymikee** 2021-04-03 07:04 UTC
Labels: bug report

**Comment by alMubarmij** [comment] 2021-05-30 12:44
I've the same issue, too!

**Comment by chriisduran** [comment] 2023-10-19 17:40
Same issue with React Native 11.3
