### ISSUE TITLE
[!] Invalid `Podfile` file: 767: unexpected token at ''. | Related Issue #448

### ISSUE THREAD

**Issue by ImAbhishekTomar** [react-native-community/cli#885] opened 2019-12-11 05:56 UTC
**Github I have already tried** : #448  

**On Stackoverflow :** https://stackoverflow.com/questions/59279777/react-native-pod-error-invalid-podfile-file-767-unexpected-token-at
**On Reddit :** https://www.reddit.com/r/reactnative/comments/e935e0/react_native_invalid_podfile_file_767_unexpected/

## Environment

System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
    Memory: 30.63 MB / 4.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A526h)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.22.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 22fb554cd53c99959f604d1ef7806e824f6cd368
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.8.4/libexec/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'quibik' do
  # Pods for quibik

  pod 'RNFBAuth', :path => "../node_modules/@react-native-firebase/auth"
  pod 'RNFBApp', :path => "../node_modules/@react-native-firebase/app"

  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'quibikTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'quibik-tvOS' do
  # Pods for quibik-tvOS

  target 'quibik-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Description
![Screenshot 2019-12-11 at 14 03 37](https://user-images.githubusercontent.com/6933841/70595747-13cd3180-1c1f-11ea-900b-ae19d1f207c5.png)

> ➜  ios git:(master) ✗ pod install --verbose
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/jack/Desktop/root in PATH, mode 040777
> 
> [!] Invalid `Podfile` file: 767: unexpected token at ''.
> 
>    from /Users/jack/Desktop/root/outonox/quibik/ios/Podfile:45
>    -------------------------------------------
>    
>  >    use_native_modules!
>    end
>    -------------------------------------------
> 
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:301:in `rescue in block in from_ruby'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:295:in `block in from_ruby'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:50:in `initialize'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:293:in `new'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:293:in `from_ruby'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:259:in `from_file'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/config.rb:200:in `podfile'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:150:in `verify_podfile_exists!'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:46:in `run'
> /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
> /usr/local/bin/pod:23:in `load'
> /usr/local/bin/pod:23:in `<main>'

## Reproducible Demo

Not sure why this is happing, but this is started after installing "@react-native-firebase" this package

**Comment by ImAbhishekTomar** [comment] 2019-12-11 06:05
added pod install --verbose

**Comment by alloy** [comment] 2019-12-18 01:59
Can you provide an example project that reproduces the problem?

**Comment by ImAbhishekTomar** [comment] 2019-12-24 13:46
i try lot to reproduces but i don't know how this is happening... finally i have created new project and migrating things in that one by one.. :(

**Comment by petarliovic** [comment] 2020-01-09 08:44
I had the same problem in Azure Devops Pipeline, I upgraded node to the latest version and that solved my problem.

**Comment by alloy** [comment] 2020-01-09 10:12
@ImAbhishekTomar Any updates on this from your end?

**Comment by gatspy** [comment] 2020-01-13 09:32
I had the same problem and finally found out that when I modified the `AndroidManifest.xml` file, I commented out some nodes which caused the execution of the 'pod instgall' command error.

**Comment by jaypeng2015** [comment] 2020-01-22 23:48
Had the same problem and then fixed by running `npm uninstall react-native-cli`

![image](https://user-images.githubusercontent.com/14153855/72944696-cfac7f80-3dcd-11ea-903a-2e1d5e2751d0.png)

**Comment by alloy** [comment] 2020-01-28 13:24
Thanks for additions, seems like it can be closed now until further notice 👍

**Closed by alloy** 2020-01-28 13:24 UTC
Labels: bug report

**Comment by A-Tokyo** [comment] 2020-01-29 16:41
My issue was that I had `react-native-cli` as a dependency, Everything worked fine once I removed it and the error didn't show up again. Hope somebody might find this useful.

**Comment by itsca** [comment] 2020-02-03 22:06
I was stuck on this exact error for about 2 days, it started for me after installing rvm, so at least in my case it appears to have been a problem with the ruby version. I encounter issues with version 2.6.3 and with the default mac version of 2.3.7. The problem stopped after cleaning rvm installation and re installing. I noticed the file worked fine on a coworker's machine running rvm with ruby 2.5.3 as default and cocoapods 1.8.4, after reinstalling rvm and emulating this environment the file worked again on my machine. Hope it helps.

**Comment by anastely** [comment] 2020-02-17 16:48
Should I remove `react-native-cli` in project root or in general? 
cuz I don't see it in package.json?

**Comment by A-Tokyo** [comment] 2020-02-17 18:18
@anastely In my case it was in package.json

I think it'd help tho if you remove it completely 👍

**Comment by raphaelrk** [comment] 2020-04-13 17:54
I removed my node_modules, Pods, and Podfile.lock, then re-ran `yarn` and `pod install` and it worked again ¯\_(ツ)_/¯

**Comment by iSanjayAchar** [comment] 2020-04-15 10:12
@raphaelrk It worked for me too

**Comment by tugzera** [comment] 2020-04-15 17:25
Same error here......

**Comment by andreasanta** [comment] 2020-04-16 14:12
> I removed my node_modules, Pods, and Podfile.lock, then re-ran `yarn` and `pod install` and it worked again ¯_(ツ)_/¯

This is the only thing that worked for me. Thank you!

**Comment by nickmurray47** [comment] 2020-04-21 14:36
> I removed my node_modules, Pods, and Podfile.lock, then re-ran `yarn` and `pod install` and it worked again ¯_(ツ)_/¯

what were your exact commands? I tried the same thing and it didn't work.

**Comment by gorkaman** [comment] 2020-04-29 20:38
This worked after I used global uninstall:  npm uninstall -g react-native-cli

**Comment by thinklinux** [comment] 2020-06-15 12:40
@raphaelrk this worked out! Thanks!

**Comment by Dustin-Hashi** [comment] 2020-08-18 17:57
@raphaelrk Thanks a bunch. You had the correct solution for me!

**Comment by deckele** [comment] 2021-01-28 09:47
I had this error caused by an old NODE_EXTRA_CA_CERTS environment variable I had sitting around. 
running:
`unset NODE_EXTRA_CA_CERTS `
worked for me.

**Comment by rafales** [comment] 2021-03-08 14:26
1. The issue here is that `use_native_modules!` hides the real issue.
2. In my case it was missing import in `react-native.config.js`.

**Comment by yatessss** [comment] 2022-04-20 03:11
> ```json
> "!**/ios/Pods/**"
> ```

its work for me, when autoAttach is smart, run pod install will ouput can not find node_modules

**Comment by israr-khan** [comment] 2022-05-11 12:59
before uninstall pod file and install again then this is working on it

**Comment by scottmas** [comment] 2022-07-10 04:43
For me, I had to remove the "execa" package. So weird

**Comment by matinzd** [comment] 2022-07-22 09:31
> yarn add @react-native-community/cli

This is so weird because react-native is using it internally and we should not install it separately. This also did not fix my problem.

```
[!] Invalid `Podfile` file: 859: unexpected token at 'Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/matin/w/dietdoctor/rnapp/node_modules/fast-check/package.json

    at new NodeError (node:internal/errors:372:5)

    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)

    at packageExportsResolve (node:internal/modules/esm/resolve:753:3)

    at resolveExports (node:internal/modules/cjs/loader:482:36)

    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)

    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)

    at Function.resolve (node:internal/modules/cjs/helpers:108:19)

    at resolveNodeModuleDir (/Users/matin/w/dietdoctor/rnapp/node_modules/@react-native-community/cli-tools/build/resolveNodeModuleDir.js:24:42)

    at /Users/matin/w/dietdoctor/rnapp/node_modules/@react-native-community/cli-config/build/loadConfig.js:93:76

    at Array.reduce (<anonymous>)
```

**Comment by ankitjainOfficial** [comment] 2022-08-01 14:45
I tried upgrading from 67.2 to 69.3 and, I'm getting a similar issue on both iOS and Android:

<details>
  <summary>iOS Build Error</summary>
  `
    [!] Invalid 'Podfile' file: 767: unexpected token at 'Error: ENOENT: no such file or directory, lstat '/Users/ankit/dev/app/mobile/ios/node_modules/@bam.tech/react-native-make'

      at Object.lstatSync (fs.js:1115:3)

      at /Users/ankit/dev/app/mobile/node_modules/graceful-fs/polyfills.js:319:16

      at Object.<anonymous> (/Users/ankit/dev/app/mobile/node_modules/@bam.tech/react-native-make/react-native.config.js:9:13)

      at Module._compile (internal/modules/cjs/loader.js:1085:14)

      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

      at Module.load (internal/modules/cjs/loader.js:950:32)

      at Function.Module._load (internal/modules/cjs/loader.js:790:14)

      at Module.require (internal/modules/cjs/loader.js:974:19)

      at require (internal/modules/cjs/helpers.js:92:18)

      at module.exports (/Users/ankit/dev/app/mobile/node_modules/cosmiconfig/node_modules/import-fresh/index.js:28:9)

    info Run CLI with --verbose flag for more details.
    '.

    from /Users/ankit/dev/app/mobile/ios/Podfile:10
    -------------------------------------------
    target 'PretaaMobile' do
    >    config = use_native_modules!
    
    -------------------------------------------
  `
</details>

<details>
  <summary>Android Build Error</Summary>
  `
    FAILURE: Build failed with an exception.

    * Where:
    Script '/Users/ankit/dev/app/mobile/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 250

    * What went wrong:
    A problem occurred evaluating script.
    > Calling '[node, /Users/ankit/dev/app/mobile/node_modules/@react-native-community/cli/build/bin.js, config]' finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
      
      The current character read is 'E' with an int value of 69
      Unable to determine the current character, it is not a string, number, array, or object
      line number 1
      index number 0
      Error: ENOENT: no such file or directory, lstat '/Users/ankit/dev/app/mobile/android/node_modules/@bam.tech/react-native-make'    at Object.lstatSync (fs.js:1115:3)    at /Users/ankit/dev/app/mobile/node_modules/graceful-fs/polyfills.js:319:16    at Object.<anonymous> (/Users/ankit/dev/app/mobile/node_modules/@bam.tech/react-native-make/react-native.config.js:9:13)    at Module._compile (internal/modules/cjs/loader.js:1085:14)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)    at Module.load (internal/modules/cjs/loader.js:950:32)    at Function.Module._load (internal/modules/cjs/loader.js:790:14)    at Module.require (internal/modules/cjs/loader.js:974:19)    at require (internal/modules/cjs/helpers.js:92:18)    at module.exports (/Users/ankit/dev/app/mobile/node_modules/cosmiconfig/node_modules/import-fresh/index.js:28:9)info Run CLI with --verbose flag for more details.
      ^. Output: Error: ENOENT: no such file or directory, lstat '/Users/ankit/dev/app/mobile/android/node_modules/@bam.tech/react-native-make'    at Object.lstatSync (fs.js:1115:3)    at /Users/ankit/dev/app/mobile/node_modules/graceful-fs/polyfills.js:319:16    at Object.<anonymous> (/Users/ankit/dev/app/mobile/node_modules/@bam.tech/react-native-make/react-native.config.js:9:13)    at Module._compile (internal/modules/cjs/loader.js:1085:14)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)    at Module.load (internal/modules/cjs/loader.js:950:32)    at Function.Module._load (internal/modules/cjs/loader.js:790:14)    at Module.require (internal/modules/cjs/loader.js:974:19)    at require (internal/modules/cjs/helpers.js:92:18)    at module.exports (/Users/ankit/dev/app/mobile/node_modules/cosmiconfig/node_modules/import-fresh/index.js:28:9)info Run CLI with --verbose flag for more details.

    * Try:
    > Run with --stacktrace option to get the stack trace.
    > Run with --info or --debug option to get more log output.
    > Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 2s
  `
</details> 


Note: What I found that the code are requesting some script, specifically `android/node_modules/@bam.tech/react-native-make` and `ios/node_modules/@bam.tech/react-native-make` from node_module folder inside platform. Which obviously, make them unavailable. 


I tried removing nodes_modules, pod, pod.lock. But, nothing fixed for me.

**Comment by matinzd** [comment] 2022-08-01 14:47
You need to wait for next cli upgrade for react native. `@bam.tech` needs to export the package json in `exports` section. 
So please reach out to maintainer and open issue there or wait until the next RN patch.
@ankitjainOfficial

**Comment by ankitjainOfficial** [comment] 2022-08-01 14:47
what options do we have till then?

**Comment by timbicker** [comment] 2022-08-03 12:52
> 1. The issue here is that `use_native_modules!` hides the real issue.
> 2. In my case it was missing import in `react-native.config.js`.

Would you be so kind as elaborate on what you exactly did to fix this error? What should I write into `react-native.config.js`?

**Comment by matfin** [comment] 2022-08-18 14:26
If anyone else is encountering an issue when running `pod install` where it complains about an unexpected token, try this.

I am in the process of updating a project to React Native 0.68.3 and I tried updating to the latest version of @react-native-community/cli (5.0.1 => 8.0.6).

I was running into a brick wall after trying many things, until I found this sample [TypeScript React Native sample](https://github.com/react-native-community/react-native-template-typescript) repo.

It seems that in their package.json file, they don't have @react-native-community/cli specified as a dependency, so I removed it as a dependency in my project.

When I re-ran `pod install` in iOS, it worked!

**Note**: I also updated to cocoapods 1.11.3.

Hope this helps others.

**Comment by pnogier** [comment] 2022-09-01 20:14
Hi @ankitjainOfficial 
Currently experiencing the exact same issue when upgrading from 0.66.4 to 0.69.5. 

Were you able to find any solution for this issue ? 

Thanks 🙏

**Comment by AndreiBacescu** [comment] 2022-09-08 11:02
In my case, I've deleted react-native-config.js and the error disappeared.

**Comment by webdevhayes** [comment] 2022-09-10 12:09
I had this issue because i removed some dependencies from my package.json and the react-native-config.js file was still referring to those dependencies. I remove them from the .js file and I was able to pod install again.

**Comment by guillaume-g** [comment] 2022-09-19 11:48
Thanks @webdevhayes, that was it!

**Comment by mrRubyDev** [comment] 2022-09-20 08:33
I tried `npm uninstall -g` but for some reason it didn't remove it. You can check your global `node_modules` folder to see if it's still there.

**Comment by umarnsisar021** [comment] 2022-10-10 06:47
I was using ``react_native_config.js`` where i disabled the react-native-permissions. but after few days i removed this library from project.. then i tried to run ``npx pod-install`` it produced the error. I tried many methods but it didn't worked for me.. So i figured out that this happening because of ``react_native_config.js`` so i delete this file it get start working.

**Comment by eyale** [comment] 2022-12-01 11:19
Had the same issue. 
Here is what helped me: 

```
rm -rf package-lock.json ./node_modules && cd ios && rm -rf Podfile.lock Pods && cd ../ && yarn && cd ios; pod deintegrate; pod install; cd ../
```

**Comment by mrRubyDev** [comment] 2022-12-01 11:21
what solved it for me was removing all the react-native-community `node_modules` that I had in my machine, not in the project itself.

**Comment by shekhardtu** [comment] 2022-12-21 09:37
> For me it was because I was using the terminal within vscode and the auto attach was breaking things, I changed my vscode settings to ignore the ios pods folder which seemed to work, disabling auto attach also works of course, my auto attach settings in my settings.json file ended up looking like this
> 
> ```json
>   "debug.javascript.autoAttachSmartPattern": [
>       "${workspaceFolder}/**",
>       "!**/node_modules/**",
>       "**/$KNOWN_TOOLS$/**",
>       "!**/ios/Pods/**"
>     ],
> ```

It worked for me. Thanks a ton

**Comment by KrisLau** [comment] 2023-01-16 16:15
My problem turned out to be in the AndroidManifest.xml:
https://github.com/facebook/react-native/issues/27205#issuecomment-554341760

Specifically:
https://stackoverflow.com/questions/71573938/react-native-error-package-name-not-found

**Comment by martijndebruijn** [comment] 2023-01-20 10:43
I simply forgot the run `npm install` before `pod install`.

**Comment by Umair-max** [comment] 2023-07-16 18:50
in my case I installed this library version npm i react-native-image-picker@5.3.1  again but  not with yarn do  it via npm .then cd ios   and pod install. then the instalation of pod worked succeccfully .

**Comment by josedaudi** [comment] 2023-08-24 21:32
> For me it was fixes when I added the package property to the AndroidManifest.xml. Somehow it got removed by the auto updater from 0.70.6 to 0.72.3
> 
> AndroidManifest.xml `<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.YOURAPPNAME">`

You are a life saver, thank you man.

**Comment by Tilesto** [comment] 2023-09-08 13:32
> For me it was because I was using the terminal within vscode and the auto attach was breaking things, I changed my vscode settings to ignore the ios pods folder which seemed to work, disabling auto attach also works of course, my auto attach settings in my settings.json file ended up looking like this
> 
> ```json
>   "debug.javascript.autoAttachSmartPattern": [
>       "${workspaceFolder}/**",
>       "!**/node_modules/**",
>       "**/$KNOWN_TOOLS$/**",
>       "!**/ios/Pods/**"
>     ],
> ```

Oh s.....
I spent few days to solve this problem. I wanted to die. Today, finally I solved the problem (just disabled auto-attach), then I found the issue on github with that problem, I wanted to write a solution, and accidentally I've seen this answer. And I missed it, when I was googling my problem( 

Anyway - thanks for the answer!) I have the same solution)

P.S. I tried it install/reinstall: pods, xCode, ruby, rvm/ruby-install, clone project many times, millions rebuild, deleting node_modules/package-lock/etc.., and many other things - but without success.

**Comment by SamiChab** [comment] 2023-11-22 17:18
Running `cd ios && pod deintegrate && pod install` solved the problem for me. As sait below (and for whatever reason), it seems that you need to have your package id in the `manifest` tag of your `AndroidManifest.xml` file in case it was deleted when upgrading RN

**Comment by DineshKachhot** [comment] 2024-02-02 01:45
For me it was a node version issue, updated node and npm to latest version worked for me,

`nvm use v21.6.1`

`nvm install-latest-npm`

**Comment by longnguyen2508** [comment] 2024-02-05 08:18
Following the upgrade to version 0.73.3, my colleague encountered an error message while using `npx pod-install`. The error message was `unexpected token at ''`, but no further details were available. After running `pod install` in the `ios` folder, I received an error message indicating that NodeJS 16.x was being used. The error was resolved after switching to version 18.x. I hope this helps!

**Comment by allenben746** [comment] 2024-03-31 03:03
> Following the upgrade to version 0.73.3, my colleague encountered an error message while using `npx pod-install`. The error message was `unexpected token at ''`, but no further details were available. After running `pod install` in the `ios` folder, I received an error message indicating that `NodeJS 16.x` was being used. The error was resolved after switching to version `18.x`. I hope this helps!

+ 1. Moving to Node 18 (`nvm use 18`) from Node 16 resolved this error on MacOS M1.

**Comment by nnabinh** [comment] 2024-05-09 06:03
> Following the upgrade to version 0.73.3, my colleague encountered an error message while using `npx pod-install`. The error message was `unexpected token at ''`, but no further details were available. After running `pod install` in the `ios` folder, I received an error message indicating that `NodeJS 16.x` was being used. The error was resolved after switching to version `18.x`. I hope this helps!

This works for me!

**Comment by nameisjayant** [comment] 2024-05-15 10:26
Also make sure , don't use vs code terminal , use system terminal to run commands

**Comment by abisalde** [comment] 2024-08-26 07:50
```bash
pod install --repo-update
```
error: unknown option '--platform'

[!] Invalid `Podfile` file: unexpected token at ''.

 #  from /Admin/Documents/Project/ios/Podfile:21
 #  -------------------------------------------
 #  target 'Project' do
 >    config = use_native_modules!
 #    flags = get_default_flags()
 #  -------------------------------------------
 
` React-Native version 0.71.14`

**Comment by szymonrybczak** [comment] 2024-08-26 07:53
hey @abisalde, it looks like you're using latest CLI where we added `--platform` version, but for some reason with older React Native version (0.71.14). Please make sure that everything is aligned, and you use appropriate CLI version to `react-native` version.

**Comment by abisalde** [comment] 2024-08-26 08:07
> hey @abisalde, it looks like you're using latest CLI where we added `--platform` version, but for some reason with older React Native version (0.71.14). Please make sure that everything is aligned, and you use appropriate CLI version to `react-native` version.

Hi @szymonrybczak, 

Can you guide me or send an article on how I can resolve this using the CLI version for 0.71.14?

**Comment by szymonrybczak** [comment] 2024-08-27 10:34
@abisalde, you can resolve which CLI version is used by running:
```
yarn why @react-native-community/cli
```
and this command will output the dependency tree with versions. 

For React Native 0.71, CLI v10 should be used. Here's a [compatibility table](https://github.com/react-native-community/cli/?tab=readme-ov-file#compatibility) which presents which CLI version should be used for which React Native version.

**Comment by phuongwd** [comment] 2024-08-29 04:53
Im using this `arch -x86_64 pod install` for

"react-native": "0.71.8"

```
phuong@Phuong ios % pod --version
1.15.2
phuong@Phuong ios % ruby --version
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin2
```

**Comment by appfr3d** [comment] 2024-10-03 07:35
> I had the same problem and finally found out that when I modified the `AndroidManifest.xml` file, I commented out some nodes which caused the execution of the 'pod instgall' command error.

I had removed a `package` tag in the `AndroidManifest.xml`, and once I added it back `pod install` suddenly worked again. 

I don't know why the two are connected? Seems very confusing to me that editing an Android specific file should affect my iOS dependency installation?

**Comment by ryuta-tanaka** [comment] 2024-10-17 05:25
>I had removed a package tag in the AndroidManifest.xml, and once I added it back pod install suddenly worked again.

This works for me!
