### ISSUE TITLE
npx react-native start: attachToServer is not a function error

### ISSUE THREAD

**Issue by dsmall89** [react-native-community/cli#1562] opened 2022-02-18 14:51 UTC
## Environment

 System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 227.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.5.2 - /usr/local/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_112 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^6.4.0 => 6.4.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found 

## Description

After running `npx react-native start` command to start metro, getting the following error:
attachToServer is not a function.
TypeError: attachToServer is not a function

<img width="904" alt="Screen Shot 2022-02-18 at 9 45 17 AM" src="https://user-images.githubusercontent.com/22219238/154704641-96c5c769-cdfa-48a5-bc5e-3c01e9134677.png">

## Reproducible Demo

**Steps to reproduce:**
1. npx react-native init AwesomeProject
2. cd AwesomeProject
3. npx react-native start

**Console log**:
TypeError: attachToServer is not a function
    at Object.runServer [as func] (/Users/x/code-workpace/react-native-workspace/pcke-react-ts/AwesomeProject/node_modules/@react-native-community/cli-plugin-metro/build/commands/start/runServer.js:131:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (/Users/x/code-workpace/react-native-workspace/pcke-react-ts/AwesomeProject/node_modules/@react-native-community/cli/build/index.js:192:9)

**Comment by hrupesh** [comment] 2022-02-18 14:56
+1

**Comment by thymikee** [comment] 2022-02-18 14:58
Duplicate of #1561

**Closed by thymikee** 2022-02-18 14:58 UTC
Labels: bug report
