### ISSUE TITLE
Support ESM `react-native.config` files

### ISSUE THREAD

**Issue by kraenhansen** [react-native-community/cli#2167] opened 2023-11-12 02:40 UTC
## Describe the Feature

I'd love to use modern ESM code in my React Native apps and libraries. The CLI's config package currently blocks having `"type": "module"` in a React Native app or library package, because the config command loads config files synchronous, with a ~ 5 year old version of `cosmiconfig`.

Setting `"type": "module"` in a `package.json` of an app or dependency yields the following error:

> error Failed to load configuration of your project.
Error [ERR_REQUIRE_ESM]: require() of ES Module {...}/rnc-cli-bug/react-native.config.js from {...}/node_modules/cosmiconfig/node_modules/import-fresh/index.js not supported.
react-native.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename react-native.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in {...}/rnc-cli-bug/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

Users cannot rename `react-native.config.js` to `react-native.config.cjs` because it's not in [the list of files being searched for](https://github.com/react-native-community/cli/blob/918e3e0f777f2046bcc7fa7862dbb1f4f0ea5d35/packages/cli-config/src/readConfigFromDisk.ts#L14), even when patching that list, yields this error:

> Error: No loader specified for extension ".cjs", so searchPlaces item "react-native.config.cjs" is invalid

So, there doesn't seem to exist any workaround for this.

## Possible Implementations

I believe the best solution is to upgrade `cosmicconfig` to a more recent version and use their async API to load the config file.
This entails that the following methods would become `async`:
- [readConfigFromDisk](https://github.com/react-native-community/cli/blob/918e3e0f777f2046bcc7fa7862dbb1f4f0ea5d35/packages/cli-config/src/readConfigFromDisk.ts#L20-L35)
- [readDependencyConfigFromDisk](https://github.com/react-native-community/cli/blob/918e3e0f777f2046bcc7fa7862dbb1f4f0ea5d35/packages/cli-config/src/readConfigFromDisk.ts#L41-L70)
- [loadConfig](https://github.com/react-native-community/cli/blob/918e3e0f777f2046bcc7fa7862dbb1f4f0ea5d35/packages/cli-config/src/loadConfig.ts#L78C10-L159)

Which would in practice break the API of both the `@react-native-community/cli` and `@react-native-community/cli-config` packages and probably require a major version bump.

A less intrusive alternative, would be to upgrade but only support CommonJS configs and simply add `react-native.config.cjs` and fix the issue loading it.

Note: Upgrading `cosmicconfig` would have the added benefit of packages being able to declare their React Native configs in their package.json files too. But that should either be disabled or named differently to avoid conflicts with the `react-native` main field already relied upon by Metro.

I'd be willing to contribute a PR to fix this, if there's a good chance it'll be considered for review.

## Related Issues

I'm surprised, but I can't seem to find existing issues mentioning this limitation.

**Comment by robhogan** [comment] 2023-11-12 13:27
FWIW, we intend to update cosmiconfig in Metro to support `metro.config.mjs` as soon as possible - one thing that's holding us back is that we ran into https://github.com/nodejs/node/issues/35889 - use of `await import` is liable to segfault Node VMs - and we were seeing this intermittently in Jest (integration tests that involved using cosmiconfig) as soon as we tried to update. I'll be trying again as soon as we've moved our CI to Node 20.

Related: https://github.com/facebook/metro/issues/916

**Comment by thymikee** [comment] 2023-11-13 09:43
@robhogan so it looks like we're blocked on Metro? Please keep us updated, we'd happily implement this

**Comment by robhogan** [comment] 2023-11-13 20:59
I wouldn't say blocked - I can't think of any technical reason this couldn't go into the CLI before Metro, although it might be less surprising if we were consistent.

I just wanted to share the experience we had with this upgrade - it *might* be that you're similarly blocked by Jest under Node<20, if you have integration tests that don't mock out cosmiconfig.

**Comment by szymonrybczak** [comment] 2023-11-14 08:22
> I just wanted to share the experience we had with this upgrade - it might be that you're similarly blocked by Jest under Node<20, if you have integration tests that don't mock out cosmiconfig.

Yes, we have - and I tried updating `cosmiconfig` and tests are failing because of this reason.

**Comment by karlhorky** [comment] 2024-01-27 13:41
> one thing that's holding us back is that we ran into [nodejs/node#35889](https://github.com/nodejs/node/issues/35889) - use of `await import` is liable to segfault Node VMs

@robhogan seems like that issue is now resolved - in case this should be noted anywhere as this blocker being removed.

**Comment by karlhorky** [comment] 2024-03-27 17:18
Ok, thanks for the answer! So I guess it's waiting until `facebook/react-native` and `facebook/metro` are on Node.js version 20? 

Taking a quick look in those repos, maybe that is tracked here?

1. https://github.com/facebook/react-native/blob/575507dd61298be2f3071e0fc01ed9715cbd7a66/.circleci/config.yml#L52
2. https://github.com/facebook/metro/blob/84956bd11ab0ded6f06a867120980f8524e9cab6/.circleci/config.yml#L12-L15

**Comment by szymonrybczak** [comment] 2024-06-26 08:22
So is there any way we can move this forward without waiting for React Native making Node.js 20 as a default version? I checked and EOL for Node.js 18 is set for 30 Apr 2025.

**Comment by szymonrybczak** [comment] 2024-07-09 14:41
hey! I've created a PR which adds support for ESM: https://github.com/react-native-community/cli/pull/2453 👍

**Comment by c100k** [comment] 2024-09-19 09:43
Thanks @szymonrybczak for the PR. Hope it will get merged soon.

In the meantime, this was the last issue we had while migrating our monorepo to ESM so we had to find a solution (see below).

**WARNING : this is a pretty ugly workaround and might not work for your use case, but in our case it does the job and unblocks us.**

```sh
# Rename to .js so it can be found and switch temporarily to commonjs
mv react-native.config.cjs react-native.config.js && sed -i '' 's/"type": "module"/"type": "commonjs"/g' package.json

# Launch the build
yarn react-native run-android

# When the Gradle tasks have started, revert the temporary changes
mv react-native.config.js react-native.config.cjs && git checkout -- package.json
```

**Comment by szymonrybczak** [comment] 2024-09-22 12:11
@c100k ah, I see 😅 I hope that you'll be able to remove this workaround soon! 👍

**Closed** 2024-11-05 08:58 UTC
Labels: feature request

**Comment by karlhorky** [comment] 2024-11-05 10:09
Copying [my comment](https://github.com/react-native-community/cli/pull/2453#issuecomment-2456747824) from the PR, since the issue is probably more visible 🤔

---

Nice, thanks to all of the contributors and reviewers here, great to have ESM in `react-native.config.js` files!

I'm not super aware of the upstreaming / integration process here in React Native projects - will this work right away out of the box with [`@react-native-community/cli@15.1.0`](https://github.com/react-native-community/cli/releases/tag/v15.1.0)?

Eg:

1. I guess new React Native projects which [start without a framework](https://reactnative.dev/docs/getting-started-without-a-framework) will receive this feature right away now?
2. Does this affect [Expo projects](https://reactnative.dev/docs/environment-setup#start-a-new-react-native-project-with-expo) at all? (I guess not)
