### ISSUE TITLE
cli not compatible with snap android-studio

### ISSUE THREAD

**Issue by bogdan-marian** [react-native-community/cli#2094] opened 2023-10-01 09:48 UTC
## Environment

```
 npx react-native info
info Fetching system and libraries information...
System:
  OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
  CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
  Memory: 23.86 GB / 31.29 GB
  Shell:
    version: 5.0.17
    path: /bin/bash
Binaries:
  Node:
    version: 18.18.0
    path: ~/.nvm/versions/node/v18.18.0/bin/node
  Yarn:
    version: 1.22.17
    path: ~/.linuxbrew/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.0/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.8.1
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

```

## Description

react-native docker is not able to detect my android studio instalation via snap and also is not able to detect my andoir SDK even if is configured correnctly

```
npx react-native doctor
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ npm - Required to install NPM dependencies

Android
 ✓ Adb - Required to verify if the android device is attached correctly
 ✓ JDK - Required to compile Java code
 ✖ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 33.0.0
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation

Errors:   2
Warnings: 0

```

```
# some extra info
snap list android-studio
Name            Version      Rev  Tracking       Publisher      Notes
android-studio  2022.3.1.18  127  latest/stable  snapcrafters✪  classic

# I have android SDK
# and this echo report the same value used by snap android studio. I can build android apps using the studio
echo $ANDROID_HOME 
/home/bogdan/Android/Sdk

# this is the end section of my $PATH
# all this are valid locations in my system
home/bogdan/Android/Sdk/emulator:/home/bogdan/Android/Sdk/tools:/home/bogdan/Android/Sdk/tools/bin:/home/bogdan/Android/Sdk/platform-tools:/home/bogdan/Android/Sdk/tools:/home/bogdan/Android/Sdk/platform-tools

```

## Reproducible Demo

install android studio using snap on ubuntu and then try to run `npx react-native doctor`

**Comment by saoudnazir** [comment] 2023-10-05 11:58
Same Issue

**Comment by Joji3110** [comment] 2023-10-08 09:19
same problem. Has anyone figured it out?

**Comment by szymonrybczak** [comment] 2023-10-08 12:49
Hey @bogdan-marian, @saoudnazir, @Joji3110, for this we're using [`envinfo`](https://www.npmjs.com/package/envinfo) package so could you please install this package globally e.g. with npm `npm install -g envinfo` and try running `envinfo --IDEs` and check if that tool found correctly path to Android Studio?

**Comment by saoudnazir** [comment] 2023-10-09 09:09
<img width="409" alt="Screenshot 2023-10-09 at 5 07 30 pm" src="https://github.com/react-native-community/cli/assets/31433177/67593c93-a6e2-4141-9a8c-2c3813162d9e">

@szymonrybczak  This is what I got.

**Comment by szymonrybczak** [comment] 2023-10-09 12:01
@saoudnazir thanks! One more thing to check, because `envinfo` detects correctly version. Could you please add `console.log(IDEs)` inside `node_modules/@react-native-community/cli-doctor/build/tools/healthchecks/androidStudio.js` in this line: 

```diff
 var _default = {
   label: 'Android Studio',
   description: 'Required for building and installing your app on Android',
   getDiagnostics: async ({IDEs}) => {
+    console.log(IDEs);
     const needsToBeFixed = IDEs['Android Studio'] === 'Not Found';
     const missing = {
       needsToBeFixed,
       version: IDEs['Android Studio'],
```

and check does it find correctly when running `envinfo` from CLI?

**Comment by szymonrybczak** [comment] 2023-10-09 20:12
@bogdan-marian thanks for checking this! I thought that you have problems with detecting Android Studio's path. Sorry for confusion. In order to investigate Android SDK problem I need two things from you.

1. Please run this command, and say if it worked correctly inside the project and outside of the project (let's say in new terminal window in root)
```
$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list
```

2. run `envinfo --SDKs`  and please please provide the output 🙏

**Comment by saoudnazir** [comment] 2023-10-16 10:24
@szymonrybczak  Sorry for the late reply.

Results for `$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list`
<img width="567" alt="Screenshot 2023-10-16 at 6 21 46 pm" src="https://github.com/react-native-community/cli/assets/31433177/ea1669e2-28db-493e-aedb-50c8f7d49502">

Results for `envinfo --SDKs `
<img width="569" alt="Screenshot 2023-10-16 at 6 22 45 pm" src="https://github.com/react-native-community/cli/assets/31433177/8efd9305-6c69-4bed-af26-48f23dffbc64">

**Comment by szymonrybczak** [comment] 2023-10-30 11:13
Duplicate of https://github.com/react-native-community/cli/issues/2079

**Closed by szymonrybczak** 2023-10-30 11:13 UTC
Labels: bug report
