### ISSUE TITLE
Error in version of template dependencies

### ISSUE THREAD

**Issue by M45ter** [react-native-community/cli#667] opened 2019-09-04 09:38 UTC
## Environment

react-navite-cli: 2.0.1
react-native: 0.59.10
pc os: win10
## Description

```sh
react-native init templateTest1 --version 0.59.10 --template common
```

common dependencies.json
```json
{
  "antd-mobile": "^2.1.8",
}
```

but in templateTest1 package.json
```json
"dependencies": {
    "antd-mobile": "2.1.8",
}
```

I think in init project package.json antd-mobile version should be ^2.1.8

**Comment by Esemesek** [comment] 2019-09-04 11:04
The issue is connected to `old` initialization flow. The [template](https://github.com/suwu150/react-native-template-common) you're using is not suitable to be used with the `new` init flow.

**Comment by Esemesek** [comment] 2019-09-04 11:12
I tried mentioned command and everything worked fine on macOS. This issue seems to be connected to the Windows platform.

**Comment by M45ter** [comment] 2019-09-05 03:53
I publish a package named react-native-template-zey-common, then run cmd
```
react-native init templateTest --version 0.59.10 --template zey-common
```
I find other bug, then the template has pictures, on windows os , it throw error like 
```
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'E:\\test\\templateTest\\node_modules\\react-native-template-zey-common\\src\\res\\img\\ic_check@3x.png'".
```
on macOS, it worked fine

**Comment by thymikee** [comment] 2020-03-09 20:56
Closing, as there's no other reports of this happening.

**Closed by thymikee** 2020-03-09 20:56 UTC
Labels: bug report, command: init compat, platform: windows
