### ISSUE TITLE
ReactNative:Cannot run program "./node_modules/.bin/react-native" (in directory "C:\Users\user\mobile\result\android\.."): CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by Jushcare** [react-native-community/cli#478] opened 2019-07-05 10:59 UTC
:ReactNative:Cannot run program "./node_modules/.bin/react-native" (in directory "C:\Users\proj_folder\android\.."): CreateProcess error=2, The system cannot find the file specified
:ReactNative:Automatic import of native modules failed.

> Configure project :app
:ReactNative:Cannot run program "./node_modules/.bin/react-native" (in directory "C:\Users\proj_folder\android\.."): CreateProcess error=2, The system cannot find the file specified
:ReactNative:Automatic import of native modules failed.

I currently using **Windows 10**
**react-native-cli:  2.0.1
react-native:  0.60.0**

Plz what can I do, I have tried all resources seen on google platform but to no avail.

**Comment by thymikee** [comment] 2019-07-05 11:01
Duplicate of https://github.com/react-native-community/cli/issues/470

**Closed by thymikee** 2019-07-05 11:01 UTC
Labels: bug

**Comment by Jushcare** [comment] 2019-07-05 11:04
So, Mr. Mike, what can I/We do to fix this bug... Plz

**Comment by thymikee** [comment] 2019-07-05 11:07
If you'd like to help, please check this question of mine and answer: https://github.com/react-native-community/cli/issues/470#issuecomment-508723151
