### ISSUE TITLE
error Failed to fetch diff for react-native@0.60.5. Maybe it's not released yet?

### ISSUE THREAD

**Issue by AireshBhat** [react-native-community/cli#720] opened 2019-09-13 19:09 UTC
## Environment

React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
      Memory: 36.62 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.7.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description

This error keeps popping up whenever I try to run the command
`react-native upgrade`

This is the output I get when I run the command
```
info No version passed. Fetching latest...
info Fetching diff between v0.59.8 and v0.60.5...
error Failed to fetch diff for react-native@0.60.5. Maybe it's not released yet?
info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#version-changes
```

**Comment by thymikee** [comment] 2019-09-15 17:46
Duplicate of #707

**Closed by thymikee** 2019-09-15 17:46 UTC
Labels: bug report
