### ISSUE TITLE
react-native link @react-native-community/async-storage  Failed to get dependency config

### ISSUE THREAD

**Issue by MarcoDo99** [react-native-community/cli#498] opened 2019-07-07 15:20 UTC
## Environment

React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 205.29 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.4.0 - ~/.nvm/versions/node/v9.4.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v9.4.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description

Hey Guys,

I am trying to install https://www.npmjs.com/package/react-native-simple-store#working-with-objects , but when trying to run 

react-native link @react-native-community/async-storage 

I get the error: 
Failed to get dependency config

When running 

react-native link @react-native-community/async-storage --verbose 

the message is 

debug Available platforms: iOS, Android
debug Targeted platforms: iOS, Android
debug Getting project config for iOS...
debug Getting project config for Android...
debug Package to link: @react-native-community/async-storage
error Failed to get dependency config
debug Error: Failed to get dependency config
    at getDependencyConfig (/.../node_modules/@react-native-community/cli/build/commands/link/getDependencyConfig.js:49:11)
    at Object.link [as func] (/.../node_modules/@react-native-community/cli/build/commands/link/link.js:97:61)
    at Promise.resolve.then (/.../node_modules/@react-native-community/cli/build/cliEntry.js:152:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3

**Comment by thymikee** [comment] 2019-07-07 15:36
Duplicate of https://github.com/react-native-community/cli/issues/273

**Closed by thymikee** 2019-07-07 15:36 UTC
Labels: bug
