### ISSUE TITLE
React Native CLI failed to determine Android project configuration. This is likely due to misconfiguration. Config output:

### ISSUE THREAD

**Issue by ckmonish2000** [react-native-community/cli#1608] opened 2022-05-13 20:39 UTC
## Ask your Question

Just created a new react-native project using npx react-native init, but after initializing the project running npx react-native run-android throws the error =>

**Android project not found. Are you sure this is a React Native project? If your Android files are located in a non-standard location (e.g. not inside 'android' folder), consider setting `project.android.sourceDir` option to point to a new location.**

while android folder is in the root dir.

I also Tried to sync the gradle files and it throws the following error =>

**java.lang.Exception: React Native CLI failed to determine Android project configuration. This is likely due to misconfiguration. Config output:**
 
i've followed various approaches from setting up a react-native react-native.config file to deleting and reinstalling node modules nothing seems to work while i'm still able to run my old react-native project.

**Comment by marqroldan** [comment] 2022-05-13 22:43
I've started experiencing this today too, but my old projects still work
Even my manually upgraded project (from 0.63.4 to 0.68.2) works too

So far, I tried initializing a new project with 0.63.4, and even that now fails too

I've tried it on a MacOS and it works there, seems like the issue is only happening on Windows OS

I've also added it to the exclusions list (just in case), but it did not do anything

I did have a Windows update 2 days ago:
- KB5013624
- KB5013942



The command I used to initialize the project is:
`$ npx react-native init RN063_4 --version 0.63.4`

Here's my `npx react-native info` (0.63.4)
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 3.20 GB / 15.93 GB
  Binaries:
    Node: 16.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210110.135312.0 - C:\devfiles\watchman-v2021.01.11.00-windows\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17763.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32413.511 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.14.1 - /c/Program Files/Eclipse Adoptium/jdk-11.0.14.101-hotspot/bin/javac
    Python: 3.9.4 - /c/Python39/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

I do have Android Studio and the sdk, it's just installed on a different drive

**Comment by marqroldan** [comment] 2022-05-13 23:42
This might be an issue with the `glob` package; I tried this sample code that looks for the AndroidManifest.xml

```
const glob = require('glob');
const path = require('path');
const fs = require('fs');

console.log(glob.sync(path.join('**', 'AndroidManifest.xml'), {
    cwd: 'android'
}))
```

With `glob@7.2.0`, it works, but with `glob@7.2.2` it fails to return anything

**Comment by ckmonish2000** [comment] 2022-05-14 04:48
@marqroldan where should i update the options

**Comment by ckmonish2000** [comment] 2022-05-14 04:57
> 
Adding resolutions in package.json worked thanks a lot @marqroldan

**Comment by marqroldan** [comment] 2022-05-14 05:02
> @marqroldan where should i update the options

It's found in `node_modules/glob/common.js` around line 114


Also, @ckmonish2000, is it alright if you leave this issue open until the maintainers can take a look? Or until the glob author responds to my comment here https://github.com/isaacs/node-glob/issues/468#issuecomment-1126590798

**Comment by nicolas377** [comment] 2022-05-14 13:28
> With glob@7.2.0, it works, but with glob@7.2.2 it fails to return anything

@marqroldan could you try overriding glob to 7.2.1 and seeing if it works?

**Comment by marqroldan** [comment] 2022-05-14 13:42
@nicolas377 Hello, 7.2.1 was never released, but setting the option `allowWindowsEscape` to `false` worked, so I was hoping that for 7.2 it would be false by default but true on 8.0

**Comment by nicolas377** [comment] 2022-05-14 16:33
This has nothing to do with [isaacs/node-glob#468](https://github.com/isaacs/node-glob/issues/468), that's a feature targeting v8. This project uses v7, which means that this is affected by [isaacs/node-glob#471](https://github.com/isaacs/node-glob/issues/471). It will be fixed by the upstream PR tied to that issue. Hopefully, the v7 branch will have the fix by today.

**Comment by azhamdev** [comment] 2022-05-14 19:29
thankss, solved for me

common.js and change options.allowWindowsEscape to false

**Comment by MarcosGoncalvesPires** [comment] 2022-05-15 03:06
There is a solution on this video...
https://www.youtube.com/watch?v=AQqYPRHTTYI
after some days lookink for I found it and it solved the issue.

**Comment by francorvalant** [comment] 2022-05-15 06:46
changing the 'options.allowWindowsEscape' to false works, I hope you fix the version soon. Thank you!

**Comment by nicolas377** [comment] 2022-05-15 14:21
Please remember that modifying node_modules is **always** a bad plan! Your edits will be overwritten every time a reinstallation takes place, and your edits will not transfer to git. I have a PR up to fix the issue on glob (isaacs/node-glob#473). Until it gets merged, please override all glob dependencies to 7.2.0 by adding the following to package.json:

```json
  "overrides": {
    "glob": "7.2.0"
  }
```

**Comment by nicolas377** [comment] 2022-05-15 16:50
Glob 7.2.3 has been released, which has fixed this issue.

**Comment by isaacs** [comment] 2022-05-15 18:34
Should be fixed by glob@7.2.3.  If it isn't, please post a new issue at https://github.com/isaacs/node-glob/issues, ideally with a reproduction case.  Thanks!

**Comment by francorvalant** [comment] 2022-05-15 19:11
> Se lanzó Glob 7.2.3, que solucionó este problema.
To upgrade just reinstall the node?

**Comment by francorvalant** [comment] 2022-05-15 19:12
> Glob 7.2.3 has been released, which has fixed this issue.

To upgrade just reinstall the node?

**Comment by nicolas377** [comment] 2022-05-15 19:15
update the glob dependency to `^7.2.3` in your package.json, then run `npm i`

package.json
```diff
  "dependencies": {
-    "glob": "^7.2.0"
+    "glob": "^7.2.3"
  }
```

**Closed** 2022-08-01 17:08 UTC
Labels: question
