### ISSUE TITLE
"--simulator" option does not work for the latest version

### ISSUE THREAD

**Issue by mustafaakb** [react-native-community/cli#1720] opened 2022-10-19 17:39 UTC
## Description

On v0.70.2 and v0.70.3 project template:
<--simulator="iPhone 14"> option does not work for any iPhone options that always launch the app default 'iPhone 8' 

I have tested on template v0.69.6 that is working as expected, launch the app on any IOS simulator which is selected as <--simulator="iPhone 12 mini"> 

## Environment

Result of "react-native info":

System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 353.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.10.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/mustafaakbas/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.1/14B47 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.2 => 0.70.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Reproducible Steps

npx react-native init awesomeproject

react-native run-ios --simulator="iPhone 12 mini"

**Comment by cortinico** [comment] 2022-10-19 17:48
Duplicate of https://github.com/react-native-community/cli/issues/1707
This is already fixed. Will be shipped in RN 0.70.4

**Closed by cortinico** 2022-10-19 17:48 UTC
Labels: bug report
