### ISSUE TITLE
Cannot destructure property `contributor` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by mi-mazouz** [react-native-community/cli#1201] opened 2020-06-14 11:09 UTC
## Environment

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 440.96 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: ~0.61.5 => 0.61.5

## Description

I just ejected my expo app and wanted to run npx @react-native-community/cli doctor but I got this error:

```
error Cannot destructure property `contributor` of 'undefined' or 'null'.
TypeError: Cannot destructure property `contributor` of 'undefined' or 'null'.
    at getHealthchecks (/Users/mickaelmazouz/.npm/_npx/29015/lib/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/index.js:40:26)
    at Object._default [as func] (/Users/mickaelmazouz/.npm/_npx/29015/lib/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:173:111)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at async Command.handleAction (/Users/mickaelmazouz/.npm/_npx/29015/lib/node_modules/@react-native-community/cli/build/index.js:184:9)
```

Any ideas? I can't find a similar issue...

**Comment by thymikee** [comment] 2020-06-14 11:22
> I can't find a similar issue...

Duplicate of #1190, it's one of the newest 🤷 

<img width="733" alt="image" src="https://user-images.githubusercontent.com/5106466/84591864-06009f00-ae42-11ea-9b73-82a4fd02ecca.png">

**Closed by thymikee** 2020-06-14 11:22 UTC
Labels: bug report

**Comment by JessikaSinanian** [comment] 2020-06-20 10:57
| Running diagnostics...error Cannot destructure property 'contributor' of 'undefined' as it is undefined. Run CLI with --verbose flag for more details.
TypeError: Cannot destructure property 'contributor' of 'undefined' as it is undefined.
    at getHealthchecks (C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject\node_modules\@react-native-community\cli\build\commands\doctor\healthchecks\index.js:41:3)
    at Object._default [as func] (C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject\node_modules\@react-native-community\cli\build\commands\doctor\doctor.js:173:111)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject\node_modules\@react-native-community\cli\build\index.js:184:9)

C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject>react-native bundle
error Option "--entry-file" is missing. Run CLI with --verbose flag for more details.
Error: Option "--entry-file" is missing
    at C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject\node_modules\@react-native-community\cli\build\tools\assertRequiredOptions.js:51:13
    at Array.forEach (<anonymous>)
    at assertRequiredOptions (C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject\node_modules\@react-native-community\cli\build\tools\assertRequiredOptions.js:40:11)
    at Command.handleAction (C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject\node_modules\@react-native-community\cli\build\index.js:181:42)
    at Command.listener (C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject\node_modules\commander\index.js:474:21)
    at setupAndRun (C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject\node_modules\@react-native-community\cli\build\index.js:259:24)
    at Object.run (C:\Users\jsinanian\AndroidStudioProjects\React_native\Myproject\node_modules\@react-native-community\cli\build\index.js:206:11)
