### ISSUE TITLE
Wrong path for static library file reference in Xcode project

### ISSUE THREAD

**Issue by bartolkaruza** [react-native-community/cli#199] opened 2019-03-03 11:37 UTC
## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 8.45 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 23, 24, 25, 26, 27, 28
        Build Tools: 21.1.2, 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 

## Description
When linking the (newly created) [@react-native-community/cameraroll](https://github.com/react-native-community/react-native-cameraroll) package to a newly generated `react-native init` project using:
```
yarn add @react-native-community/cameraroll
react-native link @react-native-community/cameraroll
```
the resulting file reference for the libRNCCameraRoll.a in the xcode project has the wrong path. The expected path is:
```
/Users/bartolkaruza/Library/Developer/Xcode/DerivedData/crollTest-cyehtgyjdklazabzboxzhmgelpyc/Build/Products/Debug-iphonesimulator/libRNCCameraRoll.a
```

The actual path:
```
/Users/bartolkaruza/dev/proj/oss/temp/crollTest/ios/libRNCCameraRoll.a
```

This leads to an 'unrecovered file reference' on linking and the library not actually being linked. The expected path I got from manually linking the product. The library project is correctly added through react-native link, just not the linking of the static library file.

## Reproducible Demo
```
react-native init temp && cd temp
yarn add @react-native-community/cameraroll
react-native link @react-native-community/cameraroll
```

**Comment by thymikee** [comment] 2019-03-03 11:47
This is a diff I get when installing cameraroll:

```diff
--- a/ios/RNtest.xcodeproj/project.pbxproj
+++ b/ios/RNtest.xcodeproj/project.pbxproj
@@ -39,6 +39,7 @@
 		ADBDB9381DFEBF1600ED6528 /* libRCTBlob.a in Frameworks */ = {isa = PBXBuildFile; fileRef = ADBDB9271DFEBF0700ED6528 /* libRCTBlob.a */; };
 		06D12EC38A5F44D998A09847 /* libRNScreens.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 223C26D23B8C4193B3EDBDAC /* libRNScreens.a */; };
 		79DC0C616A6C4382A7910733 /* libRNKeychain.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 2E889C6EE6614E23BD5844C2 /* libRNKeychain.a */; };
+		E66CA844CBD742A49F67B979 /* libRNCCameraRoll.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 6AE0F37D6740443B96BFB08A /* libRNCCameraRoll.a */; };
 /* End PBXBuildFile section */

 /* Begin PBXContainerItemProxy section */
@@ -348,6 +349,8 @@
 		223C26D23B8C4193B3EDBDAC /* libRNScreens.a */ = {isa = PBXFileReference; name = "libRNScreens.a"; path = "libRNScreens.a"; sourceTree = "<group>"; fileEncoding = undefined; lastKnownFileType = archive.ar; explicitFileType = undefined; includeInIndex = 0; };
 		932DB480169F4BEAAD918F7B /* RNKeychain.xcodeproj */ = {isa = PBXFileReference; name = "RNKeychain.xcodeproj"; path = "../node_modules/react-native-keychain/RNKeychain.xcodeproj"; sourceTree = "<group>"; fileEncoding = undefined; lastKnownFileType = wrapper.pb-project; explicitFileType = undefined; includeInIndex = 0; };
 		2E889C6EE6614E23BD5844C2 /* libRNKeychain.a */ = {isa = PBXFileReference; name = "libRNKeychain.a"; path = "libRNKeychain.a"; sourceTree = "<group>"; fileEncoding = undefined; lastKnownFileType = archive.ar; explicitFileType = undefined; includeInIndex = 0; };
+		655C455BFD184E4EA079548C /* RNCCameraRoll.xcodeproj */ = {isa = PBXFileReference; name = "RNCCameraRoll.xcodeproj"; path = "../node_modules/@react-native-community/cameraroll/ios/RNCCameraRoll.xcodeproj"; sourceTree = "<group>"; fileEncoding = undefined; lastKnownFileType = wrapper.pb-project; explicitFileType = undefined; includeInIndex = 0; };
+		6AE0F37D6740443B96BFB08A /* libRNCCameraRoll.a */ = {isa = PBXFileReference; name = "libRNCCameraRoll.a"; path = "libRNCCameraRoll.a"; sourceTree = "<group>"; fileEncoding = undefined; lastKnownFileType = archive.ar; explicitFileType = undefined; includeInIndex = 0; };
 /* End PBXFileReference section */

 /* Begin PBXFrameworksBuildPhase section */
@@ -377,6 +380,7 @@
 				139FDEF61B0652A700C62182 /* libRCTWebSocket.a in Frameworks */,
 				06D12EC38A5F44D998A09847 /* libRNScreens.a in Frameworks */,
 				79DC0C616A6C4382A7910733 /* libRNKeychain.a in Frameworks */,
+				E66CA844CBD742A49F67B979 /* libRNCCameraRoll.a in Frameworks */,
 			);
 			runOnlyForDeploymentPostprocessing = 0;
 		};
@@ -566,6 +570,7 @@
 				139FDEE61B06529A00C62182 /* RCTWebSocket.xcodeproj */,
 				EB9DCFB52958427992F2C4F4 /* RNScreens.xcodeproj */,
 				932DB480169F4BEAAD918F7B /* RNKeychain.xcodeproj */,
+				655C455BFD184E4EA079548C /* RNCCameraRoll.xcodeproj */,
 			);
 			name = Libraries;
 			sourceTree = "<group>";
@@ -1195,11 +1200,13 @@
 					"$(inherited)",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
+					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 				);
 				HEADER_SEARCH_PATHS = (
 					"$(inherited)",
 					"$(SRCROOT)/../node_modules/react-native-screens/ios",
 					"$(SRCROOT)/../node_modules/react-native-keychain/RNKeychainManager",
+					"$(SRCROOT)/../node_modules/@react-native-community/cameraroll/ios",
 				);
 			};
 			name = Debug;
@@ -1223,11 +1230,13 @@
 					"$(inherited)",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
+					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 				);
 				HEADER_SEARCH_PATHS = (
 					"$(inherited)",
 					"$(SRCROOT)/../node_modules/react-native-screens/ios",
 					"$(SRCROOT)/../node_modules/react-native-keychain/RNKeychainManager",
+					"$(SRCROOT)/../node_modules/@react-native-community/cameraroll/ios",
 				);
 			};
 			name = Release;
@@ -1252,6 +1261,7 @@
 					"$(inherited)",
 					"$(SRCROOT)/../node_modules/react-native-screens/ios",
 					"$(SRCROOT)/../node_modules/react-native-keychain/RNKeychainManager",
+					"$(SRCROOT)/../node_modules/@react-native-community/cameraroll/ios",
 				);
 			};
 			name = Debug;
@@ -1275,6 +1285,7 @@
 					"$(inherited)",
 					"$(SRCROOT)/../node_modules/react-native-screens/ios",
 					"$(SRCROOT)/../node_modules/react-native-keychain/RNKeychainManager",
+					"$(SRCROOT)/../node_modules/@react-native-community/cameraroll/ios",
 				);
 			};
 			name = Release;
@@ -1306,11 +1317,13 @@
 					"$(inherited)",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
+					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 				);
 				HEADER_SEARCH_PATHS = (
 					"$(inherited)",
 					"$(SRCROOT)/../node_modules/react-native-screens/ios",
 					"$(SRCROOT)/../node_modules/react-native-keychain/RNKeychainManager",
+					"$(SRCROOT)/../node_modules/@react-native-community/cameraroll/ios",
 				);
 			};
 			name = Debug;
@@ -1342,11 +1355,13 @@
 					"$(inherited)",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
+					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 				);
 				HEADER_SEARCH_PATHS = (
 					"$(inherited)",
 					"$(SRCROOT)/../node_modules/react-native-screens/ios",
 					"$(SRCROOT)/../node_modules/react-native-keychain/RNKeychainManager",
+					"$(SRCROOT)/../node_modules/@react-native-community/cameraroll/ios",
 				);
 			};
 			name = Release;
@@ -1377,11 +1392,13 @@
 					"$(inherited)",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
+					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 				);
 				HEADER_SEARCH_PATHS = (
 					"$(inherited)",
 					"$(SRCROOT)/../node_modules/react-native-screens/ios",
 					"$(SRCROOT)/../node_modules/react-native-keychain/RNKeychainManager",
+					"$(SRCROOT)/../node_modules/@react-native-community/cameraroll/ios",
 				);
 			};
 			name = Debug;
@@ -1412,11 +1429,13 @@
 					"$(inherited)",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 					"\"$(SRCROOT)/$(TARGET_NAME)\"",
+					"\"$(SRCROOT)/$(TARGET_NAME)\"",
 				);
 				HEADER_SEARCH_PATHS = (
 					"$(inherited)",
 					"$(SRCROOT)/../node_modules/react-native-screens/ios",
 					"$(SRCROOT)/../node_modules/react-native-keychain/RNKeychainManager",
+					"$(SRCROOT)/../node_modules/@react-native-community/cameraroll/ios",
 				);
 			};
 			name = Release;
```

Is there anything wrong with it?

**Comment by thymikee** [comment] 2019-03-03 11:52
The project builds normally for me as well. I'm using the new CLI (you'd need to install `@react-native-community/cli`), but the diff looked the same on older versions.

**Comment by thymikee** [comment] 2019-03-04 08:24
cc @grabbou @michalchudziak

**Comment by grabbou** [comment] 2019-03-04 14:35
Hmm... some paths could've been broken due to moving CLI into a subfolder of `@react-native-community`. I am going to look into it.

**Comment by thymikee** [comment] 2019-03-04 14:36
@grabbou the issue is about RN 0.58 which doesn't include the new CLI

**Comment by grabbou** [comment] 2019-03-04 14:37
Ah, right. `@react-native-community/cameraroll` is the path to camera roll. I'll see what I can do.

**Comment by bartolkaruza** [comment] 2019-03-08 11:07
Hey, I thought I'd double check that the issue is really there and below steps should make it easier to reproduce with some more output info:

```
npm install -g react-native-cli
react-native init linkTest
cd linkTest/
yarn add @react-native-community/cameraroll
yarn react-native link @react-native-community/cameraroll
```
Add the following to `App.js`:
```
...
import CameraRoll from '@react-native-community/cameraroll';
...
export default class App extends Component<Props> {

  componentDidMount = async () => {
    console.log({photos: await CameraRoll.getPhotos()});
  };
...
```
The following to `ios/linkTest/Info.plist`:
```
<dict>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>for important spy business</string>
...
```

```
yarn react-native run-ios
```

The project will compile without issues but if you see the screenshots below, the file path is not correct for the .a file from Xcode's perspective:

<img width="415" alt="screenshot 2019-03-08 at 11 50 17" src="https://user-images.githubusercontent.com/1605731/54024627-9f99c500-4198-11e9-838f-dcbef18367cb.png">
<img width="262" alt="screenshot 2019-03-08 at 11 50 26" src="https://user-images.githubusercontent.com/1605731/54024629-9f99c500-4198-11e9-82d8-fe9e1f797724.png">
<img width="262" alt="screenshot 2019-03-08 at 11 50 35" src="https://user-images.githubusercontent.com/1605731/54024631-a0325b80-4198-11e9-9e7b-a02954a3a21b.png">
<img width="538" alt="screenshot 2019-03-08 at 11 50 45" src="https://user-images.githubusercontent.com/1605731/54024632-a0325b80-4198-11e9-8795-ac638dcd8ec2.png">


Here is the diff after manually fixing the reference in Xcode and removing the 'recovered reference':
```
diff --git a/ios/linkTest.xcodeproj/project.pbxproj b/ios/linkTest.xcodeproj/project.pbxproj
index 334c94a..9fff7cc 100644
--- a/ios/linkTest.xcodeproj/project.pbxproj
+++ b/ios/linkTest.xcodeproj/project.pbxproj
@@ -36,7 +36,7 @@
                2D16E6881FA4F8E400B85C8A /* libReact.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 2D16E6891FA4F8E400B85C8A /* libReact.a */; };
                2DCD954D1E0B4F2C00145EB5 /* linkTestTests.m in Sources */ = {isa = PBXBuildFile; fileRef = 00E356F21AD99517003FC87E /* linkTestTests.m */; };
                2DF0FFEE2056DD460020B375 /* libReact.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 3DAD3EA31DF850E9000B6D8A /* libReact.a */; };
-               4F974492223281EB00340E7E /* libRNCCameraRoll.a in Frameworks */ = {isa = PBXBuildFile; fileRef = AF628BE4175D48CFA5E6DA64 /* libRNCCameraRoll.a */; };
+               4F9744E02232839300340E7E /* libRNCCameraRoll.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 4F97449122327F0800340E7E /* libRNCCameraRoll.a */; };
                832341BD1AAA6AB300B99B32 /* libRCTText.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 832341B51AAA6A8300B99B32 /* libRCTText.a */; };
                ADBDB9381DFEBF1600ED6528 /* libRCTBlob.a in Frameworks */ = {isa = PBXBuildFile; fileRef = ADBDB9271DFEBF0700ED6528 /* libRCTBlob.a */; };
                ED297163215061F000B7C4FE /* JavaScriptCore.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = ED297162215061F000B7C4FE /* JavaScriptCore.framework */; };
@@ -353,7 +353,6 @@
                78C398B01ACF4ADC00677621 /* RCTLinking.xcodeproj */ = {isa = PBXFileReference; lastKnownFileType = "wrapper.pb-project"; name = RCTLinking.xcodeproj; path = "../node_modules/react-native/Libraries/LinkingIOS/RCTLinking.xcodeproj"; sourceTree = "<group>"; };
                832341B01AAA6A8300B99B32 /* RCTText.xcodeproj */ = {isa = PBXFileReference; lastKnownFileType = "wrapper.pb-project"; name = RCTText.xcodeproj; path = "../node_modules/react-native/Libraries/Text/RCTText.xcodeproj"; sourceTree = "<group>"; };
                ADBDB91F1DFEBF0600ED6528 /* RCTBlob.xcodeproj */ = {isa = PBXFileReference; lastKnownFileType = "wrapper.pb-project"; name = RCTBlob.xcodeproj; path = "../node_modules/react-native/Libraries/Blob/RCTBlob.xcodeproj"; sourceTree = "<group>"; };
-               AF628BE4175D48CFA5E6DA64 /* libRNCCameraRoll.a */ = {isa = PBXFileReference; explicitFileType = undefined; fileEncoding = 9; includeInIndex = 0; lastKnownFileType = archive.ar; path = libRNCCameraRoll.a; sourceTree = "<group>"; };
                DCAE380E0C9F4D70AC8A2D19 /* RNCCameraRoll.xcodeproj */ = {isa = PBXFileReference; explicitFileType = undefined; fileEncoding = 9; includeInIndex = 0; lastKnownFileType = "wrapper.pb-project"; name = RNCCameraRoll.xcodeproj; path = "../node_modules/@react-native-community/cameraroll/ios/RNCCameraRoll.xcodeproj"; sourceTree = "<group>"; };
                ED297162215061F000B7C4FE /* JavaScriptCore.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = JavaScriptCore.framework; path = System/Library/Frameworks/JavaScriptCore.framework; sourceTree = SDKROOT; };
                ED2971642150620600B7C4FE /* JavaScriptCore.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = JavaScriptCore.framework; path = Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS12.0.sdk/System/Library/Frameworks/JavaScriptCore.framework; sourceTree = DEVELOPER_DIR; };
@@ -385,7 +384,7 @@
                                832341BD1AAA6AB300B99B32 /* libRCTText.a in Frameworks */,
                                00C302EA1ABCBA2D00DB3ED1 /* libRCTVibration.a in Frameworks */,
                                139FDEF61B0652A700C62182 /* libRCTWebSocket.a in Frameworks */,
-                               4F974492223281EB00340E7E /* libRNCCameraRoll.a in Frameworks */,
+                               4F9744E02232839300340E7E /* libRNCCameraRoll.a in Frameworks */,
                        );
                        runOnlyForDeploymentPostprocessing = 0;
                };
@@ -545,7 +544,6 @@
                4F97445F22327F0500340E7E /* Recovered References */ = {
                        isa = PBXGroup;
                        children = (
-                               AF628BE4175D48CFA5E6DA64 /* libRNCCameraRoll.a */,
                        );
                        name = "Recovered References";
                        sourceTree = "<group>";

```

At this point you could consider this a cosmetic issue, but I'm not sure what future issues may arise from the dangling reference in the xcode project.

**Comment by thymikee** [comment] 2019-07-08 13:21
@bartolkaruza now that RN 0.60 uses autolinking, this issue doesn't exist (it still does for earlier versions, but we'll likely not gonna touch fragile `link` logic too much). Closing.

**Closed by thymikee** 2019-07-08 13:21 UTC
