### ISSUE TITLE
ERROR: Failed to parse React Native CLI configuration.

### ISSUE THREAD

**Issue by WeTruck** [react-native-community/cli#890] opened 2019-12-16 21:37 UTC
Hello,

I'm getting this error while 'sync project through Gradle files' from Android Studio.

`ERROR: Failed to parse React Native CLI configuration. Expected running 'npx.cmd --quiet --no-install react-native config' command from '..\AwesomeProject' directory to output valid JSON, but it didn't. This may be caused by npx resolving to a legacy global react-native binary. Please make sure to uninstall any global 'react-native' binaries: 'npm uninstall -g react-native react-native-cli' and try again`

I did this which in the message,
`npm uninstall -g react-native react-native-cli`

**But it's still showing the error.**

I want to mention, it's the first sync of the project. It's just installed with this
`npx react-native init AwesomeProject`

Nothing did else.

Is there any solution?

Thanks in advance

**Comment by andremadureira1993** [comment] 2019-12-21 11:04
Hi @WeTruck 
I had run into the same issue, could you please share the full log?

Btw, in my case, what went wrong was JAVA_HOME that was set with Java instead of JDK package. Take a shot.

**Comment by fgagneten** [comment] 2019-12-28 00:15
Same issue here. Any solution?

**Comment by fgagneten** [comment] 2019-12-28 02:46
I found a temporary workaround: 
https://stackoverflow.com/a/59507720/6421759

**Comment by GoldenMaximo** [comment] 2020-01-10 14:56
I tried basically every solution I could find on GH and SO to no avail.
What worked for me:

- Delete every untracked folder/file inside of ./android
- Run `react-native start`
- Kill the process
- cd android
- gradlew clean
- Run `react-native run-android`

**Comment by croson** [comment] 2020-01-16 09:01
> I found a solution! Please see my answer at Stackoverflow:
> https://stackoverflow.com/a/59507720/6421759

It still doesn't work.

**Comment by tusharsinghal1610** [comment] 2020-01-17 14:15
delete the files it was finding error as "The current character read is 'E' with an int value of 69"
Deleting app\build\intermediates\signing_config\debug\out\signing-config.json
worked for me.

**Comment by Deathblade6** [comment] 2020-01-23 13:27
> 
> 
> delete the files it was finding error as "The current character read is 'E' with an int value of 69"
> Deleting app\build\intermediates\signing_config\debug\out\signing-config.json
> worked for me.

Worked for me too.

**Comment by grabbou** [comment] 2020-01-29 14:59
@fgagneten solution is a hack because it disables the CLI entirely. If you are having issues, please package your entire application into a `zip` and email it to me to "grabbou@gmail.com". I do really want to resolve this issue, but I am having a hard time reproducing it.

**Comment by grabbou** [comment] 2020-01-29 15:00
We are going to ship a quick update that will replace this error message with a real, underlying error. That will help debugging and eliminate hundreds of same issues that are all different.

**Comment by grabbou** [comment] 2020-01-29 15:19
Duplicate of #863 that has confirmed workaround.

**Closed by grabbou** 2020-01-29 15:19 UTC
Labels: question

**Comment by khaledBou** [comment] 2020-02-04 09:28
make sure that there's no syntax error in AndroidManifest.xml  for me i make a copy past and i forget  to close attribute with " "

**Comment by totalamd** [comment] 2020-03-09 11:11
> I found a solution! Please see my answer at Stackoverflow:
> https://stackoverflow.com/a/59507720/6421759

It's not right to like your own comment as it was someone else approved it.

**Comment by Chimaa123** [comment] 2020-06-30 07:11
For me, AndroidManifest.xml file was automatically generated in /andoird/app/release/ folder. After removing this, application compiled successfully.

**Comment by Anujmoglix** [comment] 2020-11-08 12:09
> AndroidManifest.xml

Not worked for me
