### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@react-native-community%2fcli - Not found

### ISSUE THREAD

**Issue by syedhaider03** [react-native-community/cli#1240] opened 2020-08-06 09:45 UTC
## Environment

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@react-native-community%2fcli - Not found
npm ERR! 404 
npm ERR! 404  '@react-native-community/cli@^4.7.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-native'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

## Description
npx react-native init command not working and giving error that react native community cli is not found

## Reproducible Demo
initialize a new react-native project

**Comment by vikjovanov** [comment] 2020-08-06 09:57
Same problem!
I can't complete the update of React Native because I can't update React native CLI because of this error

**Comment by shinjaeuk** [comment] 2020-08-06 10:00
Same problem from "npm i @react-native-community/....."

**Comment by talyuk** [comment] 2020-08-06 10:02
Same, can't upgrade RN to latest version

**Comment by dardinier** [comment] 2020-08-06 10:09
It seems to be a global problem with scoped packages installation from NPM registry :

https://status.npmjs.org/

Guess we'll just wait for them to fix this problem :shrug:

**Comment by JavierLaguna** [comment] 2020-08-06 10:10
I have the same issue with the 3.0.0 version

**Comment by DanielCraig01** [comment] 2020-08-06 10:21
Same issue! Hope it gets fixed soon :)

**Comment by ApexcupDeveloper** [comment] 2020-08-06 10:25
same here. I can't create new project

**Comment by khryshyn** [comment] 2020-08-06 10:26
Vendor lock!!!! Please fix it ASAP!!!

**Comment by Kirbyrawr** [comment] 2020-08-06 10:33
Working now.

**Comment by dardinier** [comment] 2020-08-06 10:33
I just tried again and NPM errors are gone :)

**Comment by DanielCraig01** [comment] 2020-08-06 10:39
Working but still exploding on required packages in my case (using typescript template)
- "@typescript-eslint/eslint-plugin@^2.25.0",
- "@typescript-eslint/parser@^2.25.0"

**Comment by Kirbyrawr** [comment] 2020-08-06 10:43
> Working but still exploding on required packages in my case (using typescript template)
> 
>     * "@typescript-eslint/eslint-plugin@^2.25.0",
> 
>     * "@typescript-eslint/parser@^2.25.0"

Same here, seems like it's still re-caching packages and maybe it didn't arrive to those yet.

**Comment by DanielCraig01** [comment] 2020-08-06 10:45
> > Working but still exploding on required packages in my case (using typescript template)
> > ```
> > * "@typescript-eslint/eslint-plugin@^2.25.0",
> > 
> > * "@typescript-eslint/parser@^2.25.0"
> > ```
> 
> Same here, seems like it's still re-caching packages and maybe it didn't arrive to those yet.

Yeah, I tried just now but it seems that the cache is broken again as I am getting an error on "@react-native-community/cli@^4.7.0" xD Fingers crossed🤞🏻

**Comment by Kirbyrawr** [comment] 2020-08-06 10:46
😅 Haha that was unexpected, thanks for the heads up..

**Comment by thymikee** [comment] 2020-08-10 08:12
Caused by npm outage, closing

**Closed by thymikee** 2020-08-10 08:12 UTC
Labels: bug report

**Comment by Ananyabharati** [comment] 2024-12-08 19:28
open the command prompt and run the following command

`npm config set legacy-peer-deps true`
