### ISSUE TITLE
adb: error: cannot bind listener: Operation not permitted

### ISSUE THREAD

**Issue by ghasemikasra39** [react-native-community/cli#437] opened 2019-06-22 08:42 UTC
## Environment

```info 
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 238.72 MB / 11.63 GB
      Shell: 5.4.2 - /bin/zsh
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
## Description

When I run `react-native run-android` the packager stops after some seconds
```
BUILD SUCCESSFUL in 2s
181 actionable tasks: 2 executed, 179 up-to-date
info Running adb -s emulator-5554 reverse tcp:8081 tcp:8081
adb: error: cannot bind listener: Operation not permitted
info Could not run adb reverse: Command failed: adb -s emulator-5554 reverse tcp:8081 tcp:8081
info Starting the app on emulator-5554 (adb -s emulator-5554 shell am start -n com.linkapverypurenative/com.linkapverypurenative.MainActivity)...
Starting: Intent { cmp=com.linkapverypurenative/.MainActivity }
```

![image](https://user-images.githubusercontent.com/24314029/59961600-3479c180-94ef-11e9-83a5-0c4e347e27f0.png)

**Comment by thymikee** [comment] 2019-06-22 08:46
Can you provide a repro we can download? Otherwise it's not actionable on our side.

**Comment by ghasemikasra39** [comment] 2019-06-25 03:42
> Can you provide a repro we can download? Otherwise it's not actionable on our side.

I cannot provide you with my repo. Its's very strange, I only get this error on my new ubuntu installation. any idea?

**Comment by odeyatwi** [comment] 2019-06-25 11:21
happend to me too, looks like android api 29 not allowing adb reverse

**Comment by thymikee** [comment] 2019-06-25 11:22
Is this a bug in adb/API29 or can we do something about it?

**Comment by anutheriddle** [comment] 2019-06-26 09:05
Well that could be the issue for adb reserve command but solution of your error is as follows :-
Steps:-
1. create a assets folder under android src/main
2. run greadlew clean command 
3. After that if you are able to see only one index.js file then run below command 

react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

4. that's it run your code

**Comment by anutheriddle** [comment] 2019-06-26 10:59
Follow below steps:-
1. adb kill-server
2. adb root

**Comment by wmertens** [comment] 2019-07-01 13:25
@anutheriddle so the problem is that the user needs root access to open a listening port? Weird… is that from a certain Android version?

**Comment by thymikee** [comment] 2020-03-09 20:47
Looks like upstream bug we can't really fix. Closing, as there's a well-established workaround for this adb issue.

**Closed by thymikee** 2020-03-09 20:47 UTC
Labels: bug report, needs repro
