### ISSUE TITLE
the metro bundle close immediately and the project didn't reload

### ISSUE THREAD

**Issue by mohammed-3li** [react-native-community/cli#494] opened 2019-07-07 00:17 UTC
In the event of a new project with four days' time, all the solutions were tested with no useful solution. If the problem was solved by the problem, the problem is that the Metro server bundle is a reaction-native run. -android opens up a second and disappears. I am a genius for four days. I have never had a sincere solution, and for knowledge I tried to change the port for live instead of 8081 for any number that is the same.

---any help plz !

Edit: any project old is play , when i create any new project didn't work .

![vCZZs](https://user-images.githubusercontent.com/33903920/60762320-55005a80-a05d-11e9-826f-88d73a44a552.png)

**Comment by Moshiour027** [comment] 2019-07-07 05:57
i experienced the same issue but if you run react-native start from another command line / terminal 
then it will work.

**Comment by gforro** [comment] 2019-07-07 06:25
The problem is caused by the unknown option "--projectRoot", which was probably removed from cli version 2, but the script launchPackager.bat file in reacte-native/script node module still use it:
`node "%~dp0..\cli.js" --projectRoot ../../../ start`

The problem is present for Windows only probably.

**Comment by Moshiour027** [comment] 2019-07-07 06:28
@gforro  yep.. are you experience eslnit  '@react-native-community' relaed problems ?

**Comment by gforro** [comment] 2019-07-07 06:30
This problem is related to issue #484. Possible fix is:
https://github.com/react-native-community/cli/issues/484#issuecomment-508792593

**Comment by thymikee** [comment] 2019-07-07 08:16
Duplicate of #484

**Closed by thymikee** 2019-07-07 08:16 UTC
Labels: question
