### ISSUE TITLE
Couldn't find template.config.js file inside "react-native" template. Please make sure the template is valid

### ISSUE THREAD

**Issue by mhmdalii** [react-native-community/cli#1637] opened 2022-07-06 12:58 UTC
## Ask your Question

Hi , 
i face this isusse once i get new macbook m1 and try all solution and doen't get any one to solve this , can any one help in this ?
<img width="663" alt="Screen Shot 2022-07-06 at 2 46 36 PM" src="https://user-images.githubusercontent.com/33903920/177555496-689faf07-2fc1-4665-b4c4-6ef2bd436de5.png">

**Comment by ReAlign** [comment] 2022-07-14 19:09
+1

**Comment by icefee** [comment] 2022-08-10 02:28
add --npm at the end of your command

**Comment by StebanDev** [comment] 2022-11-07 02:44
@icefee's solution did the trick for me.

**Comment by mrlexz** [comment] 2023-01-16 15:19
@icefee thanks

**Comment by hclj37** [comment] 2023-02-06 09:48
> add --npm at the end of your command

It works!

The reason for adding `--npm`:

> If you have both `yarn` and `npm` installed on your machine, React Native CLI will always try to use `yarn`, so even if you use `npx` utility, only `react-native` executable will be installed using `npm` and the rest of the work will be delegated to `yarn`. You can force usage of npm adding `--npm` flag to the command.

Reference:
https://github.com/react-native-community/cli/blob/main/docs/init.md#using-npx-utility

**Comment by Murtala-1** [comment] 2023-04-07 09:44
npx react-native init YourAwesomeProject --npm

you can also uninstall yarn globally
npm uninstall yarn

**Comment by jesualdo13** [comment] 2023-04-26 20:36
Definitely, Yarn is the problem. 

npx react-native init YourAwesomeProject --npm  

That worked for me

**Comment by szymonrybczak** [comment] 2023-05-05 08:22
Hey, the problem is with Yarn, to be exact the problem is Plug’n’Play, we don't support it. The solution for this is:
1. Downgrade `yarn` to v1,
2. Disable Plug’n’Play in your `yarn` config,
3. Pass `--npm` flag to init command.

**Comment by programerTala** [comment] 2023-05-08 15:16
please help me i have issue to create new react native applictaion
for more information please check [this link ](https://github.com/facebook/react-native/issues/37301)

**Comment by adamTrz** [comment] 2023-05-11 08:32
Closing the issue for now since we seem to have found a workaround for now (while we still work on proper solution 🙂 )

**Closed by adamTrz** 2023-05-11 08:32 UTC
Labels: question

**Comment by amilgasimov** [comment] 2023-05-25 05:52
> add --npm at the end of your command

thanks

**Comment by atlj** [comment] 2023-06-23 19:14
For those who don't want to uninstall yarn globally:

If you have followed the docs here https://yarnpkg.com/getting-started/install and used corepack, just run the following command:

`corepack prepare yarn@1.22.19 --activate`

**Comment by fruity4pie** [comment] 2023-07-23 17:15
Just run:

`yarn dlx react-native init mobile --npm`

`--npm` will specify `node_linker` inside the` yarnrc.yml` file.

**Comment by olawalejuwonm** [comment] 2024-03-07 09:57
> Closing the issue for now since we seem to have found a workaround for now (while we still work on proper solution 🙂 )

Is there a proper soulation now?

**Comment by szymonrybczak** [comment] 2024-03-07 10:52
hey @olawalejuwonm, you need to use Yarn with `nodeLinker: node-modules`, make sure that you're not using PnP.

**Comment by Dimon70007** [comment] 2024-09-12 13:48
I have found in React-Native documentation 

> [Optional] Using a specific version or template

```
npx react-native@X.XX.X init AwesomeProject --version X.XX.X

```

that resolved error when I tried to install 0.72.15 version of RN

```
npx react-native@0.72.15 init AwesomeProject --version 0.72.15

```

**Comment by venky145** [comment] 2024-12-16 12:13
npx @react-native-community/cli init SampleApp

this worked for me

**Comment by SauravKumar09** [comment] 2025-04-18 12:42
Use this cmd "npx @react-native-community/cli init MyApp"  100% work
