### ISSUE TITLE
`react-native start` recommends "upgrading" to a much older version

### ISSUE THREAD

**Issue by tido64** [react-native-community/cli#1617] opened 2022-05-27 12:29 UTC
## Environment

```
System:
    OS: Windows 10 10.0.22000
    CPU: (32) x64 AMD Ryzen Threadripper PRO 3955WX 16-Cores
    Memory: 114.03 GB / 127.86 GB
  Binaries:
    Node: 14.19.1 - ~\AppData\Local\Temp\yarn--1653654236904-0.6041969039767139\node.CMD
    Yarn: 1.22.11 - ~\AppData\Local\Temp\yarn--1653654236904-0.6041969039767139\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32428.217 (Visual Studio Enterprise 2019)
  Languages:
    Java: 11.0.14 - C:\Program Files\Eclipse Adoptium\jdk-11.0.14.9-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

`react-native start` recommends "upgrading" to a much older version. It also doesn't recognize canaries, `0.0.0-x`, and I suspect branches (i.e. `1000.0.0`).

This happens with `@react-native-community/cli` 8.0.2.

```
info React Native v0.60.0 is now available (your project is running on v0.0.0-20220516-2016-4994b8b5d).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.60.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.0.0-20220516-2016-4994b8b5d.
info To upgrade, run "react-native upgrade".
```

## Reproducible Demo

```
git clone https://github.com/microsoft/react-native-windows.git
cd react-native-windows
yarn
cd packages/e2e-test-app
yarn start
```

**Comment by thymikee** [comment] 2022-05-27 13:59
Can you repro it on other platforms as well?

**Comment by liamjones** [comment] 2022-05-27 15:27
It's caused by this: https://github.com/react-native-community/cli/issues/1426 (and the linked rn-diff-purge issues and PRs)

**Comment by cortinico** [comment] 2022-06-01 13:28
> info React Native v0.60.0 is now available 

Confirming that I saw this a couple of times as well

**Comment by thymikee** [comment] 2022-06-01 17:06
Closing as duplicate. Also, the corresponding issue in rn-diff-purge is resolved now, so hope it works fine

**Closed by thymikee** 2022-06-01 17:06 UTC
Labels: bug report
