### ISSUE TITLE
Cannot run android: No such file or directory, open 'app\build\intermediates\merged_manifests\debug\AndroidManifest.xml'

### ISSUE THREAD

**Issue by nicoleheard** [react-native-community/cli#967] opened 2020-02-14 01:02 UTC
## Environment

System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 1.77 GB / 7.86 GB
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Description

After creating a new react native app using the command

`npx react-native init MyAwesomeTSProject --template react-native-template-typescript`

when I run the following command

`npx react-native run-android`

I get the following message:
> info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
> Jetifier found 864 file(s) to forward-jetify. Using 4 workers...
> info Starting JS server...
> error ENOENT: no such file or directory, open 'app\build\intermediates\merged_manifests\debug\AndroidManifest.xml'. Run CLI with --verbose flag for more details.
> Error: ENOENT: no such file or directory, open 'app\build\intermediates\merged_manifests\debug\AndroidManifest.xml'
>     at Object.openSync (fs.js:440:3)
>     at Object.readFileSync (fs.js:342:35)
>     at getLaunchPackageName (C:\Workspace\MyAwesomeTSProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\getLaunchPackageName.js:161:33)
>     at buildAndRun (C:\Workspace\MyAwesomeTSProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:163:63)
>     at C:\Workspace\MyAwesomeTSProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:135:12
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async Command.handleAction (C:\Workspace\MyAwesomeTSProject\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:182:9)

## Reproducible Demo

```
npx react-native init MyAwesomeTSProject --template react-native-template-typescript
cd MyAwesomeTSProject
npx react-native run-android
```

**Comment by XELoh** [comment] 2020-02-14 01:58
I also get this error

**Comment by matejdr** [comment] 2020-02-14 02:00
Got the same thing. Any possibility of a quick fix?

**Comment by XELoh** [comment] 2020-02-14 02:17
My friend found a solution

Make sure you npm i react-native-community/cli

For android
-> go to android studio and click "sync project with gradle file"

For ios
-> cd ios and pod install

**Comment by matejdr** [comment] 2020-02-14 02:19
> My friend found a solution
> 
> Make sure you npm i react-native-community/cli
> 
> For android
> -> go to android studio and click "sync project with gradle file"
> 
> For ios
> -> cd ios and pod install

what is the version of "@react-native-community/cli-platform-android" in your node_modules directory?
```
cat node_modules/@react-native-community/cli-platform-android/package.json
```

I had to go back to 3.0.3 to get it working.

**Comment by KutoKenta** [comment] 2020-02-14 02:22
@matejdr I'm having the same problem too how did you downgrade to 3.0.3.

**Comment by XELoh** [comment] 2020-02-14 02:24
> > My friend found a solution
> > Make sure you npm i react-native-community/cli
> > For android
> > -> go to android studio and click "sync project with gradle file"
> > For ios
> > -> cd ios and pod install
> 
> what is the version of "@react-native-community/cli-platform-android" in your node_modules directory?
> 
> ```
> cat node_modules/@react-native-community/cli-platform-android/package.json
> ```
> 
> I had to go back to 3.0.3 to get it working.

my version is 3.1.1

**Comment by matejdr** [comment] 2020-02-14 02:24
add "@react-native-community/cli-platform-android": "3.0.3" to your package.json file, under dependancies

then run npm install

this is a temp solution I guess, I hope the library gets fixed in a new release and then this, lock to version, should be removed from package.json

**Comment by matejdr** [comment] 2020-02-14 02:25
yeah, 3.1.1 dow

> > > My friend found a solution
> > > Make sure you npm i react-native-community/cli
> > > For android
> > > -> go to android studio and click "sync project with gradle file"
> > > For ios
> > > -> cd ios and pod install
> > 
> > 
> > what is the version of "@react-native-community/cli-platform-android" in your node_modules directory?
> > ```
> > cat node_modules/@react-native-community/cli-platform-android/package.json
> > ```
> > 
> > 
> > I had to go back to 3.0.3 to get it working.
> 
> my version is 3.1.1

yeah, 3.1.1 does not work for me

**Comment by sitintermilan** [comment] 2020-02-14 03:43
i found a solution
package.json

"dependencies": {
   "@react-native-community/cli-platform-android": "3.0.3" //ADD
}

**Comment by marcosabb** [comment] 2020-02-14 04:13
Add this to `package.json` solved this issue for me.

```
"resolutions": {
    "@react-native-community/cli-platform-android": "3.0.3"
  }
```

**Comment by shiroze** [comment] 2020-02-14 04:43
My `package.json`
```
"dependencies": {
    "@react-native-community/cli-platform-android": "3.0.3",
    "react": "16.9.0",
    "react-native": "0.61.5",
  },
  "resolutions": {
    "@react-native-community/cli-platform-android": "3.0.3"
  },
```

Hope this solve you issue

> Copying old project is not a solution why not copied all package.json ? #hehe

**Comment by grabbou** [comment] 2020-02-14 05:56
`3.1.2` released with a fix. This issue is caused by a commit that is part of `4.x` and we specifically wanted to release it as a part of RC to have some additional time to test that change. Looks like the build caches were not properly cleared while releasing `4.x` and `3.x` with `lerna`.

I am going to start a new issue to track this down.

**Closed by grabbou** 2020-02-14 05:56 UTC
Labels: bug report

**Comment by owinter86** [comment] 2020-02-17 19:40
@grabbou I notice this error still exists while testing the RC 0.62.2 which include the updated android cli, occurs on existing projects and new init RN projects.
```
➜ yarn android
yarn run v1.22.0
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 960 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
error ENOENT: no such file or directory, open 'app/build/intermediates/merged_manifests/debug/AndroidManifest.xml'. Run CLI with --verbose flag for more details.
Error: ENOENT: no such file or directory, open 'app/build/intermediates/merged_manifests/debug/AndroidManifest.xml'
```

```
├─ @react-native-community/cli-debugger-ui@3.0.0
├─ @react-native-community/cli-platform-android@4.0.2
├─ @react-native-community/cli-platform-ios@4.1.0
├─ @react-native-community/cli-tools@3.0.0
├─ @react-native-community/cli-types@3.0.0
└─ @react-native-community/cli@4.1.0
```
